### ISSUE TITLE
Program execution error

### ISSUE THREAD

**Issue by Nilsonfsilva** [arsenetar/dupeguru#1009]
Hi !
I'm a debian contributor. I'm trying to package "dupeguru" to be part of the official debian repositories.
I managed to make the .deb package but when I run this error:

Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 33, in <module>
    sys.exit(load_entry_point('dupeGuru==4.2.1', 'console_scripts', 'dupeguru')())
  File "/usr/bin/dupeguru", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'run'

https://salsa.debian.org/nilsonfsilva/dupeguru/-/blob/master/dupeguru_4.2.1-1_amd64.deb

Can you help find out what's going on?

**Comment by arsenetar** [comment]
It seems you built that deb file following some other method than using the packaging scripts from this repository.  When I compare this deb file with those in the last release there are several differences. The packages are built normally following the instructions here https://github.com/arsenetar/dupeguru#generating-debianubuntu-package.

**Comment by Nilsonfsilva** [comment]
Everything in debian is automated.

We use delpher helpes to do the packaging.

I'll send you the configuration files so you can see
if any dependencies are missing.



Here are the building dependencies:

dh-python,
               python3-setuptools,
               python3-dev,
               python3-venv,
               pyqt5-dev-tools,
               python3-mutagen,
               python3-distro,
               python3-polib,
               python3-pyqt5,
               python3-semantic-version,
               python3-send2trash,
               python3-sphinx,
               xxhash,
               python3-pytest,
               python3-tblib,

Here are the execution dependencies:

Architecture: any
Depends: ${python3:Depends},
         ${misc:Depends},
         ${shlibs:Depends},
         python3-tblib,



Nilson F. Silva

81-3036-0200

81-991616348

81-98546-9553

________________________________
De: Andrew Senetar ***@***.***>
Enviado: domingo, 19 de junho de 2022 01:29
Para: arsenetar/dupeguru ***@***.***>
Cc: Nilsonfsilva ***@***.***>; Author ***@***.***>
Assunto: Re: [arsenetar/dupeguru] Program execution error (Issue #1009)


It seems you built that deb file following some other method than using the packaging scripts from this repository. When I compare this deb file with those in the last release there are several differences. The packages are built normally following the instructions here https://github.com/arsenetar/dupeguru#generating-debianubuntu-package.

**Comment by arsenetar** [comment]
I'm not sure that debhelper will create a good package without additional help at this time, as that is what the packaging scripts in this repository do.  The control file used by the packaging scripts is at https://github.com/arsenetar/dupeguru/blob/master/pkg/debian/control, that may be helpful.  From what you have posted here, it seems   `python3-pyqt5`, `python3-mutagen`, `python3-semantic-version` are missing from  the runtime dependencies unless they get successfully pulled into `${python3:Depends}`.

Given this is probably trying to a standard python build process that is likely part of the issue as the project does not create a good package when using those processes at this time.  It looks like the original error is most likely due to the `entry_point` script not being located in the package.
