### ISSUE TITLE
fatal error when scanning macOS photo libraries

### ISSUE THREAD

**Issue by ghost** [arsenetar/dupeguru#1028]
**Describe the bug**
I haven't had problems scanning photo libraries in the past with dupeGuru, but it's a predictable error now (see below) and the scan never completes. 

![Screenshot 2022-08-10 at 18 50 51](https://user-images.githubusercontent.com/1757768/183982063-160bc281-d11a-4a3c-becf-81ca740415f1.png)

**To Reproduce**
Add paths containing photo libraries, or just add the libraries themselves. Begin scan

**Expected behavior**
Scan should complete and present duplicates.

**Actual behaviour**
Error code with a prompt to visit GitHub 

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - dupeGuru 4.11

**Here is the output of the error: (note ,the file path referenced at "KeyError: " exists)***

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.1.1
Mac OS X Version: Version 12.5 (Build 21G72)

Traceback (most recent call last):
  File "build/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/2TB 1/Photos Library 2.photoslibrary/resources/derivatives/masters/8/826047E6-0C38-4AF6-A4D1-209B255C1719_4_5005_c.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/py/cocoa/inter.py", line 259, in pulse
  File "build/py/hscommon/gui/progress_window.py", line 105, in pulse
  File "build/py/core/app.py", line 347, in _job_error
  File "build/py/hscommon/jobprogress/performer.py", line 45, in _async_run
  File "build/py/core/app.py", line 847, in do
  File "build/py/core/scanner.py", line 145, in get_dupe_groups
  File "build/py/core/pe/scanner.py", line 27, in _getmatches
  File "build/py/core/pe/matchblock.py", line 188, in getmatches
  File "build/py/core/pe/matchblock.py", line 69, in prepare_pictures
  File "build/py/core/pe/cache_shelve.py", line 130, in purge_outdated
  File "build/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/2TB 1/Photos Library 2.photoslibrary/resources/derivatives/masters/8/826047E6-0C38-4AF6-A4D1-209B255C1719_4_5005_c.jpeg'

**Comment by glubsy** [comment]
Try removing the cache files (not sure where they are located in MacOS) and scan again.

**Comment by ghost** [comment]
That didn´t work. I compared them all visually in the end. Apologies for the late response.

**Comment by arsenetar** [comment]
This is related to the shelve cache backend which has been removed.
