### ISSUE TITLE
Crash on reading linux image dump.

### ISSUE THREAD

**Issue by EntranceJew** [arsenetar/dupeguru#1055]
**Describe the bug**
Crash on reading linux image dump.

**To Reproduce**
1. run scan on terabytes of data including a linux image dump
2. wait 4 days
3. see error

**Expected behavior**
The scan to finish.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 4.3.1

**Additional context**
log:

```
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19044-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
PermissionError: [WinError 5] Access is denied: 'Z:\\BigData\\linode\\sda\\usr\\bin\\X11\\X11\\X11\\X11\\X11\\X11\\X11\\X11\\touch'
```

**Comment by arsenetar** [comment]
Closed by 057be0294aae40bb39bcfbec51c777489b5ab1a3 which will prevent this sort of error from crashing the program.
