### ISSUE TITLE
failed to run rpm in Fedora 36

### ISSUE THREAD

**Issue by heis2201** [arsenetar/dupeguru#1066]
**Describe the bug**
the latest rpm does install in Fedora, but it doesn't start

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Version: 36

**Comment by arsenetar** [comment]
Can you provide the error encountered?  If dupeGuru does not launch at all, then launch dupeGuru from a terminal, you should be able to see an error message if the program does not open at all.

**Comment by JPnux** [comment]
Hello
I have the same problem on Fedora 37.
With dupeguru-4.3.1-2.x86_64.rpm

Error : 

❯ dupeguru
```
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'
```

**Comment by arsenetar** [comment]
@JPnux That is due to Fedora 37 having a newer system python3 version than what is supported by the rpm.

**Comment by CharAznableLoNZ** [comment]
I also ran into the python3 version issue when I upgraded to 37 and the upgrade process removed dupeguru.  Figured whatever, I'll just redownload it and be on my way.  I really like this software and am eager to use it again once a fix is pushed.

**Comment by CharAznableLoNZ** [comment]
Is there a way to fix the RPM to support the newer version of python?

**Comment by CharAznableLoNZ** [comment]
For those of us who need to still look for duplicates while we wait on a fix here, give czkawka a try.
https://github.com/qarmin/czkawka

**Comment by PJDude** [comment]
Hard to predict what will happen on countless linux distros, but You may also try this app. No installation required.
https://github.com/PJDude/dude

**Comment by CharAznableLoNZ** [comment]
czkawka is more or less portable as well.  They only ask for non-free sources so ffmpeg can be installed for video comparison to work.  The flatpak one, if you're into those, likely has all that already together.  
Either way for either program, highly recommend launching without root privileges so it can't touch anything risky.

**Comment by fretere** [comment]
Hi,
Same with Manjaro since Python 3.11

````
[marc@marc-pc ~]$ dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'
[marc@marc-pc ~]$ 


```

**Comment by fretere** [comment]
Hi,
No update planned for this?

Thanks.

Edit: the git version works.

**Comment by CharAznableLoNZ** [comment]
The git version works on Fedora 37 as well.

**Comment by IkelAtomig** [comment]
It still fails to launch in Fedora 38.

**Comment by IkelAtomig** [comment]
According to a debug.log in `~/.local/share/Hardcoded Software`

```
2023-09-12 11:21:35,278 - WARNING - Couldn't set locale en.UTF-8
2023-09-13 08:17:24,625 - WARNING - Couldn't set locale en.UTF-8
2023-09-13 19:04:47,502 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:13:44,679 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:14:13,561 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:16:19,242 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:16:32,126 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:19:27,664 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:20:42,672 - WARNING - Couldn't set locale en.UTF-8
2023-09-14 21:27:01,925 - WARNING - Couldn't set locale en.UTF-8
2023-09-15 09:52:16,438 - WARNING - Couldn't set locale en.UTF-8
2023-09-15 09:52:26,927 - WARNING - Couldn't set locale en.UTF-8
```

**Comment by CharAznableLoNZ** [comment]
Doesn't work at all in Fedora 39.  Neither the make or makeless install works.

**Comment by Ricky-Tigg** [comment]
**OS:** Fedora, edition 39. _Installed packages:_
```
$ dnf rq --installed --latest-limit 1 --qf '%{name} | %{version}' \
make automake gcc gcc-c++ python3-{pyqt5-sip,devel,virtualenv} kernel-devel | sort | column
automake | 1.16.5		make | 4.4.1
gcc | 13.2.1			python3-devel | 3.12.0
gcc-c++ | 13.2.1		python3-pyqt5-sip | 12.12.2
kernel-devel | 6.6.4		python3-virtualenv | 20.21.1
```
_Packages:_
- _not available:_ build-essential python3-pyqt5-devel python3-pyqt5 
- _available:_ python3-pyqt6-devel python3-pyqt6 | no need to install though.

Hello. Close to be good.

Ensuring that Python is up-to-date:
```
$ python -m pip install --upgrade pip
$ python3 -m venv --upgrade --system-site-packages env
```
Filtering stdout to obtain stderr:
```
$ make > /dev/null
make: msgfmt: No such file or directory
make: *** [Makefile:85: locale/ar/LC_MESSAGES/columns.mo] Error 127
```

**Comment by CharAznableLoNZ** [comment]
This is where it gets stuck for me.  I've ran both python update commands in the directory I'm installing dupeguru into.
```
(env) user@fedora:~/4TB/Applications/dupeguru$ python -m pip install --upgrade pip
Requirement already satisfied: pip in ./env/lib64/python3.12/site-packages (23.3.2)
(env) user@fedora:~/4TB/Applications/dupeguru$ python3 -m venv --upgrade --system-site-packages env
(env) user@fedora:~/4TB/Applications/dupeguru$ pip install -r requirements.txt
Ignoring PyQt5: markers 'sys_platform != "linux"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: distro>=1.5.0 in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: mutagen>=1.44.0 in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (1.46.0)
Requirement already satisfied: polib>=1.1.0 in ./env/lib64/python3.12/site-packages (from -r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: semantic-version<3.0.0,>=2.0.0 in ./env/lib64/python3.12/site-packages (from -r requirements.txt (line 6)) (2.10.0)
Requirement already satisfied: Send2Trash>=1.3.0 in ./env/lib64/python3.12/site-packages (from -r requirements.txt (line 7)) (1.8.2)
Requirement already satisfied: sphinx>=3.0.0 in ./env/lib64/python3.12/site-packages (from -r requirements.txt (line 8)) (7.2.6)
Requirement already satisfied: xxhash<4.0.0,>=3.0.0 in ./env/lib64/python3.12/site-packages (from -r requirements.txt (line 9)) (3.4.1)
Requirement already satisfied: sphinxcontrib-applehelp in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.0.7)
Requirement already satisfied: sphinxcontrib-devhelp in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.0.5)
Requirement already satisfied: sphinxcontrib-jsmath in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (2.0.4)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.1.9)
Requirement already satisfied: sphinxcontrib-qthelp in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.0.6)
Requirement already satisfied: Jinja2>=3.0 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (3.1.2)
Requirement already satisfied: Pygments>=2.14 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (2.17.2)
Requirement already satisfied: docutils<0.21,>=0.18.1 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (0.20.1)
Requirement already satisfied: snowballstemmer>=2.0 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (2.2.0)
Requirement already satisfied: babel>=2.9 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (2.14.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (0.7.13)
Requirement already satisfied: imagesize>=1.3 in ./env/lib64/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (1.4.1)
Requirement already satisfied: requests>=2.25.0 in /usr/lib/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (2.28.2)
Requirement already satisfied: packaging>=21.0 in /usr/lib/python3.12/site-packages (from sphinx>=3.0.0->-r requirements.txt (line 8)) (23.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib64/python3.12/site-packages (from Jinja2>=3.0->sphinx>=3.0.0->-r requirements.txt (line 8)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.12/site-packages (from requests>=2.25.0->sphinx>=3.0.0->-r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.12/site-packages (from requests>=2.25.0->sphinx>=3.0.0->-r requirements.txt (line 8)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.12/site-packages (from requests>=2.25.0->sphinx>=3.0.0->-r requirements.txt (line 8)) (1.26.18)
(env) user@fedora:~/4TB/Applications/dupeguru$ python build.py
Traceback (most recent call last):
  File "/home/user/4TB/Applications/dupeguru/build.py", line 20, in <module>
    from hscommon import loc
  File "/home/user/4TB/Applications/dupeguru/hscommon/loc.py", line 9, in <module>
    from hscommon import pygettext
  File "/home/user/4TB/Applications/dupeguru/hscommon/pygettext.py", line 18, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by tsilvs** [comment]
This is still an issue on Fedora 39, especially on Fedora Silverblue, because the `ln /usr/share/dupeguru/core/pre/_cache.cpython...` workaround is not possible on a read-only system.

@arsenetar @glubsy what do you think of this issue?

**Comment by Valeryan24** [comment]
Hi, is there a way to download the last git version of Dupeguru and install it on Ubuntu 24.04, in order to avoid the crash on startup due to new Python version used ? Thanks :)

**Comment by tsilvs** [comment]
Will this be fixed any time soon? Or is it time to fork?

**Comment by arsenetar** [comment]
@Valeryan24 You can follow the instructions https://github.com/arsenetar/dupeguru?tab=readme-ov-file#how-to-build-dupeguru-from-source to build from the source.

**Comment by CharAznableLoNZ** [comment]
> Will this be fixed any time soon? Or is it time to fork?

It's closing in on four years this issue has been open.  It might be time.

**Comment by jelabarre59** [comment]
The big problem with your suggested [czkawka](https://github.com/qarmin/czkawka) is it uses Gnome's intentionally-broken UI.  The interface looks wonky for those of us who refuse to use Gnome in all it's brokenness.

**Comment by feanorknd** [comment]
Hi there...

problem with latest Ubuntu noble is: compatibility with python3.12.

prebuilded deb file didn't run... it is necessary to build yourself...

- downloaded latest source code from github
- modified file hscommon/pygettext.py:
   -> replace: import imp
       with: import importlib
- make
- make run

and dupeguru is running in Ubuntu Noble... did not test all its features, but do not think there are going to be any other problems.

Ubuntu Noble python3.12 has not module "imp"... it's necessary to use "importlib".       

it would be nice developers just create a release for python3.12 systems and update current PPA with noble prebuilt packages.

Thanks everyone here!

**Comment by aswen** [comment]
The advice of @feanorknd above, combined with the advice of @arsenetar helped me to run Dupeguru on Fedora 41 with Python 3.13.1 installed.

For the [dependencies](https://github.com/arsenetar/dupeguru?tab=readme-ov-file#system-setup), I had to run:
```bash
sudo dnf install python3-qt5 python3-qt5-devel python3-virtualenv python3-devel @development-tools
```
Before I could run `make` and `make run` successfully.

Then, to be able to use, I created a desktop file `~/.local/share/applications/dupeguru.desktop`:
```
[Desktop Entry]
Type=Application
Name=dupeGuru
Exec=/data/git/others/dupeguru/env/bin/python /data/git/others/dupeguru/run.py
Icon=/data/git/others/dupeguru/images/dgpe_logo_128.png
Terminal=false
Categories=Utility;
```
Which will become visible after `update-desktop-database ~/.local/share/applications/`.

These are all workarounds, it would be cool to have the underlying problem fixed. I don't know how to that.

**Comment by fretere** [comment]
Hi,
After an update of Manjaro yesterday, dupeguru doesn't work.

`[marc@marc-pc ~]$ dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
    ...<9 lines>...
    )
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'
[marc@marc-pc ~]$ 

`
Any clue?

Thanks.

**Comment by evren320** [comment]
Same problem on Arch Linux today, in fact it was working several months ago.

I used a workaround to temporarily fix the problem for it to work on python 3.13.2
```
sudo ln -s /usr/share/dupeguru/core/pe/_cache.cpython-*-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-313-x86_64-linux-gnu.so
sudo ln -s /usr/share/dupeguru/core/pe/_block.cpython-*-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-313-x86_64-linux-gnu.so
sudo ln -s /usr/share/dupeguru/qt/pe/_block_qt.cpython-*-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-313-x86_64-linux-gnu.so
```

**Comment by fretere** [comment]
Same and i switched to dupeguru-git and it worked
