### ISSUE TITLE
error report MemoryError

### ISSUE THREAD

**Issue by TimeToFixStuff** [arsenetar/dupeguru#1075]
System with 128GB of ram and an i9. Scan done across a large network drive's storage.

Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.22621-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 152, in get_dupe_groups
  File "core\scanner.py", line 97, in _getmatches
  File "core\engine.py", line 304, in getmatches_by_contents
MemoryError

**Comment by TrashAccount3424** [comment]
I got the exact same error and I have memory usage logging on so I see that its not using up all the RAM.

However the process is slowly allocating more and more ram (who knows for what) and finally crashes at around 3700MB.
This may or may not be related to some 32-bit RAM allocation limit.
