### ISSUE TITLE
cannot move found duplicates to another folder (AttributeError in source_base)

### ISSUE THREAD

**Issue by isbjoernen** [arsenetar/dupeguru#1090]
I had found about 62 000 duplicates (photos) on an external USB disk on Kubuntu 22.04

When I had finishes reviewing the selected files I wanted to move them to another location, which failed with the following error:

Application Name: dupeGuru
Version: 4.3.1
Python: 3.10.6
Operating System: Linux-5.15.0-58-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "/usr/share/dupeguru/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
  File "/usr/share/dupeguru/core/app.py", line 332, in _job_error
    raise err
  File "/usr/share/dupeguru/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/usr/share/dupeguru/core/app.py", line 465, in do
    self.results.perform_on_marked(op, not copy)
  File "/usr/share/dupeguru/core/results.py", line 302, in perform_on_marked
    func(dupe)
  File "/usr/share/dupeguru/core/app.py", line 462, in op
    self.copy_or_move(dupe, copy, destination, desttype)
  File "/usr/share/dupeguru/core/app.py", line 439, in copy_or_move
    source_base = source_base.relative_to(location_path.relative_to(location_path.anchor))
AttributeError: 'NoneType' object has no attribute 'relative_to'

All original files were located below:
/home/art/usbDevices/WD5TbP2/home/Family-photos-and-videos

And I wanted to move the dupes to the existing yet empty folder
/home/art/usbDevices/WD5TbP2/home/Family-photos-and-videos-dupes   

/home/art/usbDevices is a softlink to /media/art/ so I tried again using the actual path as target:
 /media/art/WD5TbP2/home/Family-photos-and-videos-dupes
with the same result

I made another attempt to move it to a different partition on the same physical usb disk:
 /media/art/WD5TbP1/family-fotos-dupes
again producing the same error message.

I made a final attempt freeing space on my local hard disk attempting to move the dupes to that location:
/home/art/family-fotos-dupes

And again the same error:
Application Name: dupeGuru
Version: 4.3.1
Python: 3.10.6
Operating System: Linux-5.15.0-58-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "/usr/share/dupeguru/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
  File "/usr/share/dupeguru/core/app.py", line 332, in _job_error
    raise err
  File "/usr/share/dupeguru/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/usr/share/dupeguru/core/app.py", line 465, in do
    self.results.perform_on_marked(op, not copy)
  File "/usr/share/dupeguru/core/results.py", line 302, in perform_on_marked
    func(dupe)
  File "/usr/share/dupeguru/core/app.py", line 462, in op
    self.copy_or_move(dupe, copy, destination, desttype)
  File "/usr/share/dupeguru/core/app.py", line 439, in copy_or_move
    source_base = source_base.relative_to(location_path.relative_to(location_path.anchor))
AttributeError: 'NoneType' object has no attribute 'relative_to'

To Reproduce:
- Have many files marked (here: 62000)
- Choose in the Menu: Actions -> Move Marked to
- choose any empty, existing destination on local or usb disk with sufficient free space (>137Gbyte in my case) and say "Ok"
- An error box with the above text pops up

**Expected behavior**
- selected files being moved into the selected target directory, but that is not happening
- 
DupeGuru Version used: "About" reports 4.3.1

Environment:
Kubuntu 22.04
uname -r : 5.15.0-58-generic
python3 --version
Python 3.10.6
KDE Plasma Version: 5.24.7
Frameworks: 5.92.0
Qt version: 5.15.3
Kernel: 5.15.0-58-generic
Graphics: X11

**Comment by glubsy** [comment]
Thanks for reporting.
Quick question: does the error message pop up right after clicking "OK" to move? Nothing gets moved at all then? (I suspect yes)
Does it happen with only a coupe of marked files? (I suspect no)
That's a lot of marked files... have you marked them all automatically, or was it a manual process?
Was is the only operation you attempted or did you do any other operation beforehand?

**Comment by isbjoernen** [comment]
Hi,
and thanks for looking into this..
- error message pops up immediately. No file is moved
- I would have to test in the evening - I don't have everything at the
office
- if it were only a few files, I would not bother with software....that is
the whole point of the exercise ;-)
I started with letting dupeGuru hunt for all dupes. Then I ordered the
results by percentage of match and manually reviewed all files with <99%
agreement and the first few hundred with 99% the rest I left as suggested
with all remaining dupes marked.

Then I tried to move the marked files.....to no avail.

Thanks.

**Comment by isbjoernen** [comment]
Hi,

To reply to your comment arsenetar@dupeguru:

_Quick question: does the error message pop up right after clicking "OK" to move? Nothing gets moved at all then? (I suspect yes)
Does it happen with only a coupe of marked files? (I suspect no)
That's a lot of marked files... have you marked them all automatically, or was it a manual process?_

Hi and thanks for looking into this..
- error message pops up immediately. No file is moved
- I would have to test in the evening - I don't have everything at the office
- if it were only a few files, I would not bother with software....that is the whole point of the exercise ;-)
I started with letting dupeGuru hunt for all dupes. Then I ordered the results by percentage of match and manually reviewed all files with <99% agreement and the first few hundred with 99% the rest I left as suggested with all remaining dupes marked.

Then I tried to move the marked files.....to no avail.

Thanks

**Comment by isbjoernen** [comment]
I tried with only 5 files marked (loading the saved results, then un-marking all, then marking 5 dupes)
Action-> move files   failed with the same error as reported originally. The number of marked files seems to make no difference.

I may try to install Anaconda with python 3.9... perhaps it will make a difference to 3.10 used at system level.....

**Comment by isbjoernen** [comment]
Hi,

I installed Anaconda 3.9 and built dupeguru release 4.3.1 from source within that older python environment and then loaded my saved dupeguru results and tried to move it as explained earlier.
Well, I do get the same error.

Application Name: dupeGuru
Version: 4.3.1
Python: 3.9.13
Operating System: Linux-5.15.0-58-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/core/app.py", line 332, in _job_error
    raise err
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/core/app.py", line 465, in do
    self.results.perform_on_marked(op, not copy)
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/core/results.py", line 302, in perform_on_marked
    func(dupe)
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/core/app.py", line 462, in op
    self.copy_or_move(dupe, copy, destination, desttype)
  File "/home/art/software/dupeGuru/src/dupeguru-4.3.1/core/app.py", line 439, in copy_or_move
    source_base = source_base.relative_to(location_path.relative_to(location_path.anchor))
AttributeError: 'NoneType' object has no attribute 'relative_to'

Any ideas for a workaround or fix?!
Many thanks

**Comment by isbjoernen** [comment]
workaround...
I built version 4.2.1 from source inside Anaconda 3.9 and that moved the zillion files as expected!
Hence my little task is completed. DupeGuru 4.3.1 found 62,000 dupes in a total of 307,000 photos and version 4.2.1 moved the marked dupes as expected.
Thanks.
