### ISSUE TITLE
Waited for Hours, then crashed.  Here's the report it produced

### ISSUE THREAD

**Issue by MikeyMoMo** [arsenetar/dupeguru#1099]
I probably overran your memory capabilities.  It was a very large tree.

Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 152, in get_dupe_groups
  File "core\scanner.py", line 97, in _getmatches
  File "core\engine.py", line 304, in getmatches_by_contents
MemoryError

**Comment by arsenetar** [comment]
This error generally happens when your system runs out of memory.
