### ISSUE TITLE
Dupeguru crashed after 12 hours of comparing two 2TB hdd

### ISSUE THREAD

**Issue by simmival** [arsenetar/dupeguru#1137]
Error Report:
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
OSError: [WinError 1392] The file or directory is corrupted and unreadable: 'D:\\AdobeCatBkup\\B0110173.json'

Not sure if this is a bug or normal behaviour..

**Comment by glubsy** [comment]
This is an operating system error. Apparently that file is corrupted. 

Perhaps Dupeguru should not crash on such error though, rather simply display a warning.

**Comment by simmival** [comment]
No problem.  I can read it via notepad ok..   Perhaps a message flagging it corrupt rather than abort might be better..  Especially if one is comparing a large number of files..
