### ISSUE TITLE
dupeguru cannot be installed with pip

### ISSUE THREAD

**Issue by cebtenzzre** [arsenetar/dupeguru#1145]
Command: `pip install git+https://github.com/arsenetar/dupeguru.git`
Warnings while running the command:
```
ERROR: For req: dupeGuru==4.3.1. Invalid script entry point: <ExportEntry dupeguru = run.py:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```
Result:
```
$ dupeguru
Traceback (most recent call last):
  File "/home/cebtenzzre/.local/bin/dupeguru", line 5, in <module>
    from run import main
ModuleNotFoundError: No module named 'run'
```
Command: `SETUPTOOLS_ENABLE_FEATURES='legacy-editable' pip install -e git+https://github.com/arsenetar/dupeguru.git#egg=dupeguru`
Result:
```
$ dupeguru
Traceback (most recent call last):
  File "/home/cebtenzzre/.local/bin/dupeguru", line 33, in <module>
    sys.exit(load_entry_point('dupeGuru', 'console_scripts', 'dupeguru')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cebtenzzre/.local/bin/dupeguru", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cebtenzzre/src/src/dupeguru/run.py", line 19, in <module>
    from qt import dg_rc  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'dg_rc' from 'qt' (/home/cebtenzzre/src/src/dupeguru/qt/__init__.py)
```

Also, when installed in editable mode, dupeGuru's `build` folder shadows the `build` package, which is used to build python packages.

**Comment by arsenetar** [comment]
Yes, as it currently is right now dupeGuru is not expected to be installed via pip.

**Comment by cebtenzzre** [comment]
It does work if you clone the repo, run make, and then run `SETUPTOOLS_ENABLE_FEATURES='legacy-editable' pip install -e .`. But then you can't use `python -m build` anymore because of the name conflict. Without legacy-editable, you still get the exception:
```
Traceback (most recent call last):
  File "/home/cebtenzzre/.local/bin/dupeguru", line 5, in <module>
    from run import main
ModuleNotFoundError: No module named 'run'
```

**Comment by cebtenzzre** [comment]
For context, the reason I would like to do this is that I have a fork that uses Pillow and av to find duplicate videos by generating thumbnails. But Arch Linux provides Pillow 10.0.0, which [dropped PyQt5 support](https://pillow.readthedocs.io/en/stable/deprecations.html#pyqt5-and-pyside2) in the ImageQt class. I'd like to avoid downgrading my system Pillow just to install the package... I guess I'll have to fork Pillow too.

**Comment by arsenetar** [comment]
Understandable, unfortunately as it stands at this moment dupeGuru does not support installing via pip, even if may be possible.  There are a series of issues with trying to use via normal tooling and pip as of right now.
