### ISSUE TITLE
Throw error instead of crashing.

### ISSUE THREAD

**Issue by pinballelectronica** [arsenetar/dupeguru#1149]
If you have a previously mounted Bitlocker drive and you exit out, if you reload the program it remembers that drive.  If that drive is not mounted, program will throw an immediate error when loading and crash.  Recommend throwing an error instead of crashing if you intend to keep the last used drive in cache.

Great program.

**Comment by onzebleu** [comment]
Error message: 
Traceback (most recent call last):
  File "run.py", line 88, in <module>
  File "run.py", line 75, in main
  File "qt\app.py", line 56, in __init__
  File "qt\app.py", line 101, in _setup
  File "core\app.py", line 573, in load
  File "core\directories.py", line 257, in load_from_file
  File "core\directories.py", line 159, in add_path
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
OSError: [WinError -2144272384] This drive is locked by BitLocker Drive Encryption. You must unlock this drive from Control Panel: 'D:\\data'

Closing the warning box closes the app.
