### ISSUE TITLE
Error when i move or copy all duplicates files

### ISSUE THREAD

**Issue by jasolerolmos** [arsenetar/dupeguru#1165]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by jasolerolmos** [comment]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.11.2
Operating System: Linux-6.1.0-12-amd64-x86_64-with-glibc2.36

Traceback (most recent call last):
  File "/home/jose/Descargas/github/dupeguru/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jose/Descargas/github/dupeguru/core/app.py", line 330, in _job_error
    raise err
  File "/home/jose/Descargas/github/dupeguru/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/home/jose/Descargas/github/dupeguru/core/app.py", line 463, in do
    self.results.perform_on_marked(op, not copy)
  File "/home/jose/Descargas/github/dupeguru/core/results.py", line 302, in perform_on_marked
    func(dupe)
  File "/home/jose/Descargas/github/dupeguru/core/app.py", line 460, in op
    self.copy_or_move(dupe, copy, destination, desttype)
  File "/home/jose/Descargas/github/dupeguru/core/app.py", line 437, in copy_or_move
    source_base = source_base.relative_to(location_path.relative_to(location_path.anchor))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'relative_to'
