### ISSUE TITLE
hscommon\pygettext.py calling imp, which is removed in 3.12

### ISSUE THREAD

**Issue by rbennett00** [arsenetar/dupeguru#1170]
imp is no longer available in 3.12 and has been replaced with importlib. need to update pygettext.py to use importlib instead.

(env) C:\Users\rbenn\Documents\GitHub\dupeguru>py build.py
Traceback (most recent call last):
  File "C:\Users\rbenn\Documents\GitHub\dupeguru\build.py", line 20, in <module>
    from hscommon import loc
  File "C:\Users\rbenn\Documents\GitHub\dupeguru\hscommon\loc.py", line 9, in <module>
    from hscommon import pygettext
  File "C:\Users\rbenn\Documents\GitHub\dupeguru\hscommon\pygettext.py", line 18, in <module>
    import imp
**ModuleNotFoundError: No module named 'imp'**

**Comment by dktrkranz** [comment]
Patch fixing this issue can be found here: https://github.com/python/cpython/commit/328cb1fed0c91f50f311cdc545fe0e9303d0dae7#diff-27bf55510663a73d2fdea1e604efdb59e0115378530202b5c55d04656dedece2
