### ISSUE TITLE
erreor while compering files from 3 disks...

### ISSUE THREAD

**Issue by 42tomato** [arsenetar/dupeguru#1189]
As you will see issue occurred while I tried to compare photos from 3 different disks, further, they were disks of different kinds. C: is an internal SSD D: is a memory card in a side slot and E: is an external HDD. I wouldn't bother reporting this but the error message was very convincing.
Below screenshot and ctrl C>V bug report.
"Ther requested operation requires elevation." I can run it as admin?
All the best, love your work. T.

Device name	LAPTOP-IPDM04RL
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
Installed RAM	16,0 GB (15,7 GB usable)
Device ID	9D301C15-6ACC-4FDF-ABCE-6DD6C81103D6
Product ID	00330-50000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

Edition	Windows 10 Pro
Version	22H2
Installed on	‎05.‎01.‎2024
OS build	19045.3930
Serial number	R90WVZ0V
Experience	Windows Feature Experience Pack 1000.19053.1000.0

![Screenshot (1)](https://github.com/arsenetar/dupeguru/assets/53923555/c34f230c-02ff-4bcb-9787-8486d81e02c3)

Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 152, in get_dupe_groups
  File "core\pe\scanner.py", line 27, in _getmatches
  File "core\pe\matchblock.py", line 196, in getmatches
  File "multiprocessing\context.py", line 119, in Pool
  File "multiprocessing\pool.py", line 212, in __init__
  File "multiprocessing\pool.py", line 303, in _repopulate_pool
  File "multiprocessing\pool.py", line 326, in _repopulate_pool_static
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 327, in _Popen
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 72, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 73, in __init__
OSError: [WinError 740] The requested operation requires elevation

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by 42tomato** [comment]
Sorry I tried to follow the instructions I found but, I'm more like a coder "wanna be". I can't give you more information. That laptop was sent for repairs (I broke the keyboard.)
