### ISSUE TITLE
Module core.pe.photo is missing

### ISSUE THREAD

**Issue by All-The-Foxes** [arsenetar/dupeguru#1191]
DupeGuru will not open because the core.pe.photo module is missing. This is on Ubuntu Mantic (23.10)

Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'

**Comment by fretere** [comment]
Hi,
Same her since Plasma 6:

```
[marc@marc-pc ~]$ dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/lib/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/lib/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/lib/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
  File "/usr/lib/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'
[marc@marc-pc ~]$ 
```

**Comment by 6xthFNGR** [comment]
Same.
Ubuntu 24.04

> uname -a
> Linux 6.8.0-45-lowlatency #45.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux


> dupeguru -v
> QSocketNotifier: Can only be used with threads started with QThread
> Traceback (most recent call last):
>   File "/usr/bin/dupeguru", line 88, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/bin/dupeguru", line 71, in main
>     from qt.app import DupeGuru
>   File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
>     from core.app import AppMode, DupeGuru as DupeGuruModel
>   File "/usr/share/dupeguru/core/app.py", line 27, in <module>
>     from core.pe.photo import get_delta_dimensions
> ModuleNotFoundError: No module named 'core.pe.photo'


> dupeguru 4.3.1-4build1
> Python 3.12.3
> pip3 install -r dupeguru/requirements.txt - Successful
> pip3 list
> alabaster                     0.7.16
> babel                         2.16.0
> certifi                       2024.8.30
> charset-normalizer            3.3.2
> distro                        1.9.0
> docutils                      0.21.2
> idna                          3.10
> imagesize                     1.4.1
> Jinja2                        3.1.4
> MarkupSafe                    2.1.5
> mutagen                       1.47.0
> packaging                     24.1
> pip                           24.0
> polib                         1.2.0
> Pygments                      2.18.0
> PyQt5                         5.15.11
> PyQt5-Qt5                     5.15.15
> PyQt5_sip                     12.15.0
> requests                      2.32.3
> semantic-version              2.10.0
> Send2Trash                    1.8.3
> setuptools                    75.1.0
> snowballstemmer               2.2.0
> Sphinx                        7.4.7
> sphinxcontrib-applehelp       2.0.0
> sphinxcontrib-devhelp         2.0.0
> sphinxcontrib-htmlhelp        2.1.0
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-qthelp          2.0.0
> sphinxcontrib-serializinghtml 2.0.0
> urllib3                       2.2.3
> xxhash                        3.5.0

Depending if I install system-wide or in a Python Virtual Environment, I get different issues.
I guess due to different dependencies and dupeguru builds.


System-Wide
> dupeguru
> Traceback (most recent call last):
>   File "/usr/local/bin/dupeguru", line 33, in <module>
>     sys.exit(load_entry_point('dupeGuru==4.3.1', 'console_scripts', 'dupeguru')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/dupeguru", line 25, in importlib_load_entry_point
>     return next(matches).load()
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
>     module = import_module(match.group('module'))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'run'


VENV
> dupeguru
> QSocketNotifier: Can only be used with threads started with QThread
> Traceback (most recent call last):
>   File "/usr/bin/dupeguru", line 88, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/bin/dupeguru", line 71, in main
>     from qt.app import DupeGuru
>   File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
>     from core.app import AppMode, DupeGuru as DupeGuruModel
>   File "/usr/share/dupeguru/core/app.py", line 27, in <module>
>     from core.pe.photo import get_delta_dimensions
> ModuleNotFoundError: No module named 'core.pe.photo'


I dont know where to get the module 'core.pe.photo' yet. The dependencies where installed as recommended.

More similar reports: https://github.com/arsenetar/dupeguru/issues/1255

**Comment by jonapoul** [comment]
Same here:
```sh
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'
```

It was working fine a few weeks ago - my Python version is 3.12.3 for reference

**Comment by raspyThomas** [comment]
I'm not sure where the real reason is, but on Ubuntu 24.04 dupeguru package is strangly split apart.
Main appication is placed here:

   `/usr/share/dupeguru`

but some bits and pieces are here:

   `/usr/lib/dupeguru`

Likely this lib path contains some python modules written in C for performance.

Yet this lib folder is not on my standard python path:
Currently i only have the following, when running dupeguru:

  ```
   /usr/share/dupeguru
   /usr/lib/python312.zip
   /usr/lib/python3.12
   /usr/lib/python3.12/lib-dynload
   /usr/local/lib/python3.12/dist-packages
   /usr/lib/python3/dist-packages
```

Thus the error can be worked around by:

```
   sudo cp -r /usr/lib/dupeguru/qt/pe/* /usr/share/dupeguru/qt/pe/
   sudo cp -r /usr/lib/dupeguru/core/pe/* /usr/share/dupeguru/core/pe/
```
After doing this it works again. 
Yet the real cause for this packaging issue must be somewhere else. I'm not sure where exactly.
