### ISSUE TITLE
Error with scanning files

### ISSUE THREAD

**Issue by Timothea8530** [arsenetar/dupeguru#1193]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\All Users\\Microsoft\\Windows\\Containers\\BaseImages\\d2c64894-d522-45a4-bb36-04fee8ba7d05\\BaseLayer\\Files\\Users\\All Users\\Microsoft\\Windows\\Containers\\BaseImages\\d2c64894-d522-45a4-bb36-04fee8ba7d05\\BaseLayer\\Files\\Windows\\INF\\prnms007.inf'

**Comment by NWinocur** [comment]
Encountered similar today when scanning files:

`Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
OSError: [WinError 1920] The file cannot be accessed by the system: 'H:\\ProgramData\\Microsoft\\Windows\\Containers\\BaseImages\\90c96b4a-382b-4cb6-88d2-7fed4f1fc054\\BaseLayer\\Files\\Users\\All Users\\Microsoft\\Windows\\Containers\\BaseImages\\32dca643-59b0-4a36-be93-1dc85a05f9cf\\BaseLayer\\Files\\Windows\\System32\\help.exe'
`

See also: https://github.com/arsenetar/dupeguru/issues/1237
