### ISSUE TITLE
Cannot delete or move files from NAS

### ISSUE THREAD

**Issue by cjburkha** [arsenetar/dupeguru#1201]
I scanned for dupes and found like 18k works great, love the preivew for images

The majority of them I was able to delete by moving to local disk and sending to trash. (I tried send to trash and got an error)

For 840 of them I cannot delete. After a scan and selecting 333 of them I choose"Move Marked To...:". The files get copied but not removed from NAS.

I was able to move and trash all of the original 18K except these 840. After first run I went into settings and gave dupeguru full disk access, still cannot delete the 840.
![problems](https://github.com/arsenetar/dupeguru/assets/640009/61a2a992-df2e-49d8-9b85-b65e7e7990f9)
![problems2](https://github.com/arsenetar/dupeguru/assets/640009/8b3825c8-128f-4c52-9347-795e86cab184)

**Desktop (please complete the following information):**
MacMini M1 14.1.1 (23B81)

Debug Log
2024-02-19 07:26:17,334 - WARNING - Couldn't set locale en
2024-02-19 07:26:17,604 - WARNING - Error while loading /Users/chrisb/Library/Application Support/Hardcoded Software/dupeGuru/exclude_list.xml: [Errno 2] No such file or directory: '/Users/chrisb/Library/Application Support/Hardcoded Software/dupeGuru/exclude_list.xml'
2024-02-19 07:28:54,533 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,533 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,533 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,534 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,534 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,534 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,534 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,541 - WARNING - Couldn't set locale en
2024-02-19 07:28:54,542 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,403 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,403 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,403 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,403 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,403 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,404 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,404 - WARNING - Couldn't set locale en
2024-02-19 09:08:11,404 - WARNING - Couldn't set locale en
2024-02-19 14:31:47,489 - WARNING - Couldn't set locale en
**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by shawnmarks8** [comment]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.9.2
Operating System: macOS-15.2-arm64-arm-64bit

Traceback (most recent call last):
  File "hscommon/gui/progress_window.py", line 107, in pulse
  File "core/app.py", line 332, in _job_error
  File "hscommon/jobprogress/performer.py", line 46, in _async_run
  File "core/app.py", line 465, in do
  File "core/results.py", line 302, in perform_on_marked
  File "core/app.py", line 462, in op
  File "core/app.py", line 439, in copy_or_move
AttributeError: 'NoneType' object has no attribute 'relative_to'

similar issue ^^^ cannot move all duplicates to a custom folder
