### ISSUE TITLE
Memory error scanning a particular folder

### ISSUE THREAD

**Issue by pantropia** [arsenetar/dupeguru#1208]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.22631-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 152, in get_dupe_groups
  File "core\scanner.py", line 97, in _getmatches
  File "core\engine.py", line 304, in getmatches_by_contents
MemoryError

App does not close properly after the memory error - shows as still running in task manager. 
Debug log ends with 
2024-03-01 07:56:29,403 - DEBUG - Collected 0 files in folder D:\For Deduping\C
2024-03-01 07:56:29,403 - INFO - Scanning 1290200 files
2024-03-01 07:56:32,185 - INFO - Getting matches. Scan type: 5
2024-03-01 12:21:29,992 - DEBUG - Debug mode enabled

I assume that last line was when the app had been restarted after the crash. 
I'll break it down into sections and try again.

**Comment by pantropia** [comment]
...ah. Seeing as it found over 65000 very small rubbish dupes in a subsection, I see why it wasn't having a fun time.

**Comment by pantropia** [comment]
I've been too busy with other things to look at the deduping recently, but I'm back at it. I had an out of memory error trying to de-dupe a different folder, and as previously tried to do the subfolders first and then do the whole lot together. 
I have a vague memory of finding a folder which had gone recursive previously, but all the subfolders scanned OK, so I didn't think it could be that, but it still crashed when I tried to do the whole lot together again. One of the folders had a lot of zero-size files in it (probably due to being a failed copy of a folder on a failing linux NAS which I think is what caused the recursive folder also) which I thought might be the problem, so I used another app to find all the zero-size files and empty folders and shift them off to another folder. I ran dupeguru on that folder and it coped fine, identifying all the files as duplicates. It was also able to deduplicate the folder which had been throwing memory errors before. I've scanned other folders which have more files than that folder (even before the zero-size ones were removed) so I'm still none the wiser.

**Comment by pantropia** [comment]
OK I think I found the issue and it's not in the folder I thought it was in:
There's a folder which contains a backup of a failing VM with a mailserver on it. I'd overlooked it because it was so small, but it was small because nearly all the files are empty.  Under 400MB, over 200,000 files. Presumably nearly all identical. I can see how that would choke DupeGuru. 
I'm currently running an old app which deletes empty folders and files on there. Yes I know I could do it with powershell, I would rather throw stuff to the recycle bin *just in case*. I was wondering: Would it be possible to do an initial pass which identifies and removes zero-size files from a folder before attempting any further deduping? The old app I'm using, being old, is Not Quick.
