### ISSUE TITLE
FAILED AT SCANNING

### ISSUE THREAD

**Issue by Nesxy137** [arsenetar/dupeguru#1210]
**Describe the bug**
I hit explore and it crashes

**To Reproduce**
Just hit explore and it throws the error.

**Expected behavior**
Should have explored and worked properly.

**Screenshots**
![image](https://github.com/arsenetar/dupeguru/assets/162034608/4857ad14-c610-46a9-ae62-8616cf479f69)

**Desktop (please complete the following information):**
windows 11

**Additional context**
this the failure log: 

Application Name: dupeGuru
Version: 4.3.1
Python: 3.12.2
Operating System: Windows-11-10.0.22621-SP0

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\pe\matchblock.py", line 127, in async_compare
    ref_pairs = list(cache.get_multiple(ref_ids))  # (rowid, [b, b2, ..., b8])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\pe\cache_sqlite.py", line 163, in get_multiple
    cur = self.con.execute(sql)
          ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "1": syntax error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\dupeguru-master\hscommon\gui\progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\app.py", line 330, in _job_error
    raise err
  File "C:\Users\User\Desktop\dupeguru-master\hscommon\jobprogress\performer.py", line 46, in _async_run
    target(*args)
  File "C:\Users\User\Desktop\dupeguru-master\core\app.py", line 821, in do
    self.results.groups = scanner.get_dupe_groups(files, self.ignore_list, j)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\scanner.py", line 150, in get_dupe_groups
    matches = self._getmatches(files, j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\pe\scanner.py", line 28, in _getmatches
    return matchblock.getmatches(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\dupeguru-master\core\pe\matchblock.py", line 222, in getmatches
    collect_results()
  File "C:\Users\User\Desktop\dupeguru-master\core\pe\matchblock.py", line 179, in collect_results
    matches += result.get()
               ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
sqlite3.OperationalError: near "1": syntax error

**Comment by arsenetar** [comment]
Fixed by https://github.com/arsenetar/dupeguru/commit/a81069be61677958b273fad891f8ef097f715209
