### ISSUE TITLE
Python crash

### ISSUE THREAD

**Issue by rkazak** [arsenetar/dupeguru#1213]
**Describe the bug**

Python appears to have crashed while doing a search and comparison in picture mode.

**To Reproduce**

TBD - just started to do a comparison and this happened

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**

Application Name: dupeGuru
Version: 4.3.1
Python: 3.12.2
Operating System: macOS-14.3.1-x86_64-i386-64bit

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/pe/matchblock.py", line 127, in async_compare
    ref_pairs = list(cache.get_multiple(ref_ids))  # (rowid, [b, b2, ..., b8])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/pe/cache_sqlite.py", line 163, in get_multiple
    cur = self.con.execute(sql)
          ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "1": syntax error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rkazak/dupeguru/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/app.py", line 330, in _job_error
    raise err
  File "/Users/rkazak/dupeguru/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/Users/rkazak/dupeguru/core/app.py", line 821, in do
    self.results.groups = scanner.get_dupe_groups(files, self.ignore_list, j)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/scanner.py", line 150, in get_dupe_groups
    matches = self._getmatches(files, j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/pe/scanner.py", line 28, in _getmatches
    return matchblock.getmatches(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkazak/dupeguru/core/pe/matchblock.py", line 223, in getmatches
    collect_results(collect_all=True)
  File "/Users/rkazak/dupeguru/core/pe/matchblock.py", line 179, in collect_results
    matches += result.get()
               ^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
sqlite3.OperationalError: near "1": syntax error

**Comment by rkazak** [comment]
Also even though the app stayed up, the crash did not take it down completely however I am unable to do any type of scans ( standard, Music, Picture ). It looks like it needs to be restarted.

**Comment by arsenetar** [comment]
Fixed by https://github.com/arsenetar/dupeguru/commit/a81069be61677958b273fad891f8ef097f715209
