### ISSUE TITLE
dupeGuru refuses to start on Fedora 39 Plasma Desktop spin.

### ISSUE THREAD

**Issue by GhostCoder22** [arsenetar/dupeguru#1217]
dupeGuru refuses to start on Fedora 39 Plasma Desktop spin whenever I tried launching it from KDE's Application Launcher, so I tried starting it directly from Konsole instead only to be presented with the following traceback:

> Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'

**Python version 3.1.2** is installed.

1.  Attempt to start dupeGuru either from the desktop or Konsole.

**Expected behavior**

1.  dupeGuru should normally start.

![dupeGuru Traceback](https://github.com/arsenetar/dupeguru/assets/13742124/651bb9ff-da28-40e0-aa89-a2baed0962ff)

As of this bug report, the following was reported by **Info Center**:

- **Operating System**: Fedora Linux 39
- **KDE Plasma Version**: 5.27.11
- **KDE Frameworks Version**: 5.115.0
- **Qt Version**: 5.15.12
- **Kernel Version**: 6.7.9-200.fc39.x86_64 (64-bit)
- **Graphics Platform**: Wayland
- **Processors**: 4 × Intel® Core™ i3-7100U CPU @ 2.40GHz
- **Memory**: 15.4 GiB of RAM
- **Graphics Processor**: Mesa Intel® HD Graphics 620

**Comment by Valeryan24** [comment]
Hi, same here on Ubuntu 24.04 (pre-beta) with Python 3.12 - Dupeguru doesn't start : 

`$ dupeguru
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'`

**Comment by CharAznableLoNZ** [comment]
Seems to be the same at https://github.com/arsenetar/dupeguru/issues/1066

**Comment by sylvainfaivre** [comment]
Borrowed from the linked issue, here is the fix for Ubuntu 24.04 / Python 3.12 :  

```
cd /usr/share/dupeguru/core/pe
sudo ln -s  _cache.cpython-310-x86_64-linux-gnu.so _cache.cpython-312-x86_64-linux-gnu.so
sudo ln -s _block.cpython-310-x86_64-linux-gnu.so _block.cpython-312-x86_64-linux-gnu.so
cd ../../qt/pe
sudo ln -s _block_qt.cpython-310-x86_64-linux-gnu.so _block_qt.cpython-312-x86_64-linux-gnu.so

```
