### ISSUE TITLE
Process crashes after analyzing pictures

### ISSUE THREAD

**Issue by TimHabeck** [arsenetar/dupeguru#1220]
**Describe the bug**
I wanted to deduplicate a collection of images. The program analyzed about 3.5k photos and when it wanted to start comparing them (I assume) the process crashed. The window did not crash though. I did this multiple times and it crashes every time. I started the programm not by installing it regularly but instead I created a python virtual environment, installed all dependencies in it and then run the run.py file. It used to work before, this is the first time that I use Picture mode though.

**To Reproduce**
1. Start dupeGuru
2. Choose Picture Mode
3. Choose Folder
4. Press Scan
5. Wait for the analyze step to finish

**Expected behavior**
I expected it to compare my analyzed pictures next.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Version 4.3.1

**traceback**
Application Name: dupeGuru
Version: 4.3.1
Python: 3.12.2
Operating System: Linux-6.8.4-200.fc39.x86_64-x86_64-with-glibc2.38

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/pe/matchblock.py", line 127, in async_compare
    ref_pairs = list(cache.get_multiple(ref_ids))  # (rowid, [b, b2, ..., b8])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/pe/cache_sqlite.py", line 163, in get_multiple
    cur = self.con.execute(sql)
          ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "2": syntax error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/Downloads/dupeguru/hscommon/gui/progress_window.py", line 107, in pulse
    should_continue = self._error_func(self.jobid, err)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/app.py", line 330, in _job_error
    raise err
  File "/home/username/Downloads/dupeguru/hscommon/jobprogress/performer.py", line 46, in _async_run
    target(*args)
  File "/home/username/Downloads/dupeguru/core/app.py", line 821, in do
    self.results.groups = scanner.get_dupe_groups(files, self.ignore_list, j)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/scanner.py", line 150, in get_dupe_groups
    matches = self._getmatches(files, j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/pe/scanner.py", line 28, in _getmatches
    return matchblock.getmatches(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Downloads/dupeguru/core/pe/matchblock.py", line 222, in getmatches
    collect_results()
  File "/home/username/Downloads/dupeguru/core/pe/matchblock.py", line 179, in collect_results
    matches += result.get()
               ^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
sqlite3.OperationalError: near "2": syntax error

**Comment by josephmudrak** [comment]
I’m having the same issue – Fedora 40, Python 3.12.2. The only difference is that the traceback states near "1", not near "2".

**Comment by arsenetar** [comment]
This should be fixed by https://github.com/arsenetar/dupeguru/commit/a81069be61677958b273fad891f8ef097f715209
