### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by ripplesouth** [arsenetar/dupeguru#1225]
**Describe the bug**
memory error while scanning for dupes. scan halts. 64 million files to dedupe.

**To Reproduce**
1. select multiple drives to scan
2. After scan running over 48 hours
3. popup with error message

**Expected behavior**
Report duplicate files

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: server 2019 fully updated
 - Version 1809

Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.17763-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 152, in get_dupe_groups
  File "core\scanner.py", line 97, in _getmatches
  File "core\engine.py", line 304, in getmatches_by_contents
MemoryError

**Comment by YEAS175m3** [comment]
Exact same error/traceback message here with the following differences in the initial situation:

- Windows 10 Pro 22H2 (Build 19045.4291)
- Application Mode: Standard
- Scan Type: Folders  (with Filter Hardness 100)

Only 1 directory (Backup folder with 12 TB and 1550000 files.
