### ISSUE TITLE
WinError

### ISSUE THREAD

**Issue by waterboymuz** [arsenetar/dupeguru#1237]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 107, in pulse
  File "core\app.py", line 332, in _job_error
  File "hscommon\jobprogress\performer.py", line 46, in _async_run
  File "core\app.py", line 820, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
  File "pathlib.py", line 1407, in exists
  File "pathlib.py", line 1198, in stat
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\All Users\\Microsoft\\Windows\\Containers\\BaseImages\\d3d0a561-57ca-4a79-a0d0-58dc41d41e9e\\BaseLayer\\Files\\Users\\All Users\\Microsoft\\Windows\\Containers\\BaseImages\\d3d0a561-57ca-4a79-a0d0-58dc41d41e9e\\BaseLayer\\Files\\Windows\\SysWOW64\\GameInput.dll'

**Comment by TurnOffNOD** [comment]
I have the same issue.
