### ISSUE TITLE
DUPEGURU

### ISSUE THREAD

**Issue by JBORGES74** [arsenetar/dupeguru#1241]
**Describe the bug**
A clear and concise descrApplication Name: dupeGuru
Version: 4.3.1
Python: 3.9.2
Operating System: macOS-14.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "qt/app.py", line 365, in preferencesTriggered
  File "qt/preferences_dialog.py", line 296, in load
TypeError: setText(self, str): argument 1 has unexpected type 'int'
iption of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by JBORGES74** [comment]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.9.2
Operating System: macOS-14.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "qt/app.py", line 365, in preferencesTriggered
  File "qt/preferences_dialog.py", line 296, in load
TypeError: setText(self, str): argument 1 has unexpected type 'int'
