### ISSUE TITLE
Can't Start on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by Koorosh-J** [arsenetar/dupeguru#1255]
After upgrading my os to ubuntu 24.04.1 I can not start dupeguru

From bash I get the following lines:

~$ dupeguru 
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'

 - OS: Ubuntu 24.04.1
 - Dupeguru Version 4.3.1

Thanks in advance

**Comment by 6xthFNGR** [comment]
Double post see https://github.com/arsenetar/dupeguru/issues/1191

Use Proper Headlines and search before you post.
As the last line of your code says: _ModuleNotFoundError: No module named 'core.pe.photo'_
Add this to the title please so others find it more easily.

**Comment by silvain** [comment]
For me, Dupeguru crashes on Ubuntu 24.04 with 
File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'

**Comment by jeffhoffman13** [comment]
Issue still happens perhaps a typo core.photo instead of core.pe.photo?  Which does not find core.pe.photo on the system.

ubuntu 24.10

$ sudo dupeguru -v
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 27, in <module>
    from core.pe.photo import get_delta_dimensions
ModuleNotFoundError: No module named 'core.pe.photo'
