### ISSUE TITLE
Errno 13 Permission denied

### ISSUE THREAD

**Issue by johnwarm** [arsenetar/dupeguru#281]
```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "C:\src\dupeguru\core\app.py", line 467, in export_to_csv
  File "C:\src\dupeguru\core\export.py", line 146, in export_to_csv
PermissionError: [Errno 13] Permission denied: '.csv'
```

**Comment by hsoft** [comment]
Very similar to #266
