### ISSUE TITLE
Database disk image is malformed - how to fix?

### ISSUE THREAD

**Issue by restlessmonkey** [arsenetar/dupeguru#311]
Get the following after updating to the latest version of dupeguru PE and OSX:

```
Application Identifier: com.hardcoded-software.dupeguru-pe
Application Version: 2.10.1
Mac OS X Version: Version 10.10.3 (Build 14D136)

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 103, in _create_con
sqlite3.OperationalError: no such column: mtime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 92, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 59, in reraise_if_error
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru PE.app/Contents/Resources/py/core/app.py", line 743, in do
  File "build/dupeGuru PE.app/Contents/Resources/py/core/scanner.py", line 134, in get_dupe_groups
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/scanner.py", line 21, in _getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 160, in getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 57, in prepare_pictures
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 40, in __init__
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 105, in _create_con
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 96, in create_tables
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by hsoft** [comment]
Ideally, dupeGuru should fix it automatically (which is why I classify this ticket as a bug), but meanwhile, you should be able to work around that error by doing "Clear picture cache". Did you try that?

**Comment by restlessmonkey** [comment]
Hi - I've literally have had no problems with dupeguru until this one so I didn't even know about that option :-)  Sadly, got this error when I did the "Clear picture cache" - I'm open to suggestions.

Application Identifier: com.hardcoded-software.dupeguru-pe
Application Version: 2.10.1
Mac OS X Version: Version 10.10.3 (Build 14D136)

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 103, in _create_con
sqlite3.OperationalError: no such column: mtime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/inter/app_pe.py", line 319, in clearPictureCache
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/scanner.py", line 28, in clear_picture_cache
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 40, in __init__
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 105, in _create_con
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 96, in create_tables
sqlite3.DatabaseError: database disk image is malformed

**Comment by hsoft** [comment]
Oh, you'll have to manually delete the cache file, which is in the `~/Library/Application Support` folder (which Apple, in its grand wisdom, decided to hide from its users and this thus hard to access). I don't remember the exact path though...

**Comment by restlessmonkey** [comment]
That did it! Thank you!
It was in the users directory.
Jim
