### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ElliottVL** [arsenetar/dupeguru#313]
```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 724, in do
  File "C:\src\dupeguru\core\scanner.py", line 128, in get_dupe_groups
  File "C:\src\dupeguru\core_pe\scanner.py", line 21, in _getmatches
  File "C:\src\dupeguru\core_pe\matchblock.py", line 157, in getmatches
  File "C:\src\dupeguru\core_pe\matchblock.py", line 58, in prepare_pictures
  File "C:\src\dupeguru\core_pe\cache.py", line 154, in purge_outdated
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'K:\\0 MARGIN FOR ERROR PIX  PROCESSING 2\\mariage110709 142 (8).jpg'
```

**Comment by arsenetar** [comment]
This is a rather old version, I am closing all issues related to versions 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
