### ISSUE TITLE
Memory Error while scanning

### ISSUE THREAD

**Issue by BigGeorgeTx** [arsenetar/dupeguru#317]
This is the first time I have tried to use dupeguru.

Here is the error message:

```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 743, in do
  File "C:\src\dupeguru\core\scanner.py", line 134, in get_dupe_groups
  File "C:\src\dupeguru\core\scanner.py", line 85, in _getmatches
  File "C:\src\dupeguru\core\engine.py", line 275, in getmatches_by_contents
MemoryError
```

I found two other references to MemoryError, but they appear closed, so I am opening a new issue.

This was a very large scan.  It ran for about 12 hours and seemed to stop making progress when it was 77% complete, having found over 170,000 potentially duplicate files.  I did the scan of the entire harddrive.

**Comment by hsoft** [comment]
Thanks for the report. It's always a good idea to link to similar tickets for a better context, so here we go: #264 and #58.

**Comment by hsoft** [comment]
Also, this is probably a matter of digging in old commits and restoring `MemoryError` handling logic. As I write in #264, I got rid of all that logic when going full 64bit, thinking it was impossible to get memory errors now, but obviously, I was wrong.

**Comment by Anderman** [comment]
I have also an memory error

Application Name: dupeGuru Picture Edition
Version: 2.10.1


```
Traceback (most recent call last):
  File "C:\src\dupeguru\core_pe\matchblock.py", line 189, in getmatches
  File "C:\src\dupeguru\core_pe\matchblock.py", line 150, in collect_results
  File "C:\Python33\lib\multiprocessing\pool.py", line 568, in get
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 724, in do
  File "C:\src\dupeguru\core\scanner.py", line 128, in get_dupe_groups
  File "C:\src\dupeguru\core_pe\scanner.py", line 21, in _getmatches
  File "C:\src\dupeguru\core_pe\matchblock.py", line 198, in getmatches
MemoryError

```

**Comment by hsoft** [comment]
It should be noted that the Windows version of dupeGuru is [currently unmaintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted)

**Comment by arsenetar** [comment]
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.
