### ISSUE TITLE
Able to build/run under OSX but not when edition PE

### ISSUE THREAD

**Issue by salamanders** [arsenetar/dupeguru#340]
Fresh pull from github, can build and run the standard edition fine on OSX using the bootstrap file, but can't do the PE.

```
$ . env/bin/activate && python configure.py --edition pe && python build.py && python run.py
Configuring dupeGuru PE for UI cocoa (Release)
Building dupeGuru PE with UI cocoa
Building dupeGuru
Building PE Modules
running build_ext
copying build/lib.macosx-10.6-x86_64-3.3/_block.so -> 
copying build/lib.macosx-10.6-x86_64-3.3/_cache.so -> 
copying build/lib.macosx-10.6-x86_64-3.3/_block_osx.so -> 
Moving _block.so --> core_pe/_block.so
Moving _block_osx.so --> core_pe/_block_osx.so
Moving _cache.so --> core_pe/_cache.so
Creating OS X app structure
Copying build/Info.plist --> build/dupeGuru PE.app/Contents/Info.plist
Building localizations
Creating lproj folders based on .po files
Creating build/dupeGuru PE.app/Contents/Resources/cs.lproj/Localizable.strings from locale/cs/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/cs.lproj/cocoalib.strings from cocoalib/locale/cs/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/de.lproj/Localizable.strings from locale/de/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/de.lproj/cocoalib.strings from cocoalib/locale/de/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/es.lproj/Localizable.strings from locale/es/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/es.lproj/cocoalib.strings from cocoalib/locale/es/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/fr.lproj/Localizable.strings from locale/fr/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/fr.lproj/cocoalib.strings from cocoalib/locale/fr/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/hy.lproj/Localizable.strings from locale/hy/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/hy.lproj/cocoalib.strings from cocoalib/locale/hy/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/it.lproj/Localizable.strings from locale/it/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/it.lproj/cocoalib.strings from cocoalib/locale/it/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/ko.lproj/Localizable.strings from locale/ko/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/ko.lproj/cocoalib.strings from cocoalib/locale/ko/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/nl.lproj/Localizable.strings from locale/nl/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/nl.lproj/cocoalib.strings from cocoalib/locale/nl/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/pl_PL.lproj/Localizable.strings from locale/pl_PL/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/pl_PL.lproj/cocoalib.strings from cocoalib/locale/pl_PL/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/pt_BR.lproj/Localizable.strings from locale/pt_BR/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/pt_BR.lproj/cocoalib.strings from cocoalib/locale/pt_BR/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/ru.lproj/Localizable.strings from locale/ru/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/ru.lproj/cocoalib.strings from cocoalib/locale/ru/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/uk.lproj/Localizable.strings from locale/uk/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/uk.lproj/cocoalib.strings from cocoalib/locale/uk/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/vi.lproj/Localizable.strings from locale/vi/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/vi.lproj/cocoalib.strings from cocoalib/locale/vi/LC_MESSAGES/cocoalib.po
Creating build/dupeGuru PE.app/Contents/Resources/zh_CN.lproj/Localizable.strings from locale/zh_CN/LC_MESSAGES/ui.po
Creating build/dupeGuru PE.app/Contents/Resources/zh_CN.lproj/cocoalib.strings from cocoalib/locale/zh_CN/LC_MESSAGES/cocoalib.po
Copying cocoa/base/en.lproj/Localizable.strings --> build/dupeGuru PE.app/Contents/Resources/en.lproj
Copying cocoalib/en.lproj/cocoalib.strings --> build/dupeGuru PE.app/Contents/Resources/en.lproj
Building xibless UIs
Building Python extensions
Building Cocoa Proxy
running build_ext
building 'CocoaProxy' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -Icocoalib -Icocoa/autogen -I/Users/ME/Documents/code/dupeguru/env/include -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c cocoalib/cocoa/CocoaProxy.m -o build/temp.macosx-10.6-x86_64-3.3/cocoalib/cocoa/CocoaProxy.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -Icocoalib -Icocoa/autogen -I/Users/ME/Documents/code/dupeguru/env/include -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c build/CocoaProxy.m -o build/temp.macosx-10.6-x86_64-3.3/build/CocoaProxy.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -Icocoalib -Icocoa/autogen -I/Users/ME/Documents/code/dupeguru/env/include -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c build/ObjP.m -o build/temp.macosx-10.6-x86_64-3.3/build/ObjP.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -Icocoalib -Icocoa/autogen -I/Users/ME/Documents/code/dupeguru/env/include -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c cocoalib/HSErrorReportWindow.m -o build/temp.macosx-10.6-x86_64-3.3/cocoalib/HSErrorReportWindow.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -Icocoalib -Icocoa/autogen -I/Users/ME/Documents/code/dupeguru/env/include -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c cocoa/autogen/HSErrorReportWindow_UI.m -o build/temp.macosx-10.6-x86_64-3.3/cocoa/autogen/HSErrorReportWindow_UI.o
/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-x86_64-3.3/cocoalib/cocoa/CocoaProxy.o build/temp.macosx-10.6-x86_64-3.3/build/CocoaProxy.o build/temp.macosx-10.6-x86_64-3.3/build/ObjP.o build/temp.macosx-10.6-x86_64-3.3/cocoalib/HSErrorReportWindow.o build/temp.macosx-10.6-x86_64-3.3/cocoa/autogen/HSErrorReportWindow_UI.o -o build/lib.macosx-10.6-x86_64-3.3/CocoaProxy.so -framework CoreFoundation -framework Foundation -framework AppKit -framework CoreServices
copying build/lib.macosx-10.6-x86_64-3.3/CocoaProxy.so -> 
Moving CocoaProxy.so --> cocoalib/cocoa/CocoaProxy.so
Building Cocoa Bridging Interfaces
Traceback (most recent call last):
  File "build.py", line 398, in <module>
    main()
  File "build.py", line 395, in main
    build_normal(edition, ui, dev, conf)
  File "build.py", line 355, in build_normal
    build_cocoa(edition, dev)
  File "build.py", line 125, in build_cocoa
    build_cocoa_bridging_interfaces(edition)
  File "build.py", line 304, in build_cocoa_bridging_interfaces
    appmod = importlib.import_module('inter.app_{}'.format(edition))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1586, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1567, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1534, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/ME/Documents/code/dupeguru/cocoa/inter/app_pe.py", line 26, in <module>
    from core_pe.iphoto_plist import IPhotoPlistParser
  File "/Users/ME/Documents/code/dupeguru/core_pe/iphoto_plist.py", line 11, in <module>
    class IPhotoPlistParser(plistlib._PlistParser):
AttributeError: 'module' object has no attribute '_PlistParser'
(env) ~/Documents/code/dupeguru @ MEmacbook (ME) $ 
```

**Comment by hsoft** [comment]
Python's minimum requirements on OS X are 10.7 and Python 3.4. You seem to be on Python 3.3 on 10.6. If you go back one minor version back (pe2.9.0), it should work.

**Comment by salamanders** [comment]
Shouldn't that be covered by the bootstrap.sh checks?

**Comment by hsoft** [comment]
Yes, ideally. This is why this issue is a bug: the bootstrap script should fail with a meaningful error message.

**Comment by arsenetar** [comment]
PE edition no longer exists.
