### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by kowalenko** [arsenetar/dupeguru#356]
```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 743, in do
  File "C:\src\dupeguru\core\scanner.py", line 134, in get_dupe_groups
  File "C:\src\dupeguru\core\scanner.py", line 85, in _getmatches
  File "C:\src\dupeguru\core\engine.py", line 275, in getmatches_by_contents
MemoryError
```

**Comment by netjunki** [comment]
I got a similar error running on Windows 7 with a fairly large directory tree.

```
Application Name: dupeGuru
Version: 3.9.0

Traceback (most recent call last):
File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 95, in pulse
File "C:\Python33\lib\site-packages\jobprogress\performer.py", line 59, in reraise_if_error
File "C:\Python33\lib\site-packages\jobprogress\performer.py", line 43, in _async_run
File "C:\src\dupeguru\core\app.py", line 724, in do
File "C:\src\dupeguru\core\scanner.py", line 158, in get_dupe_groups
File "C:\src\dupeguru\core\engine.py", line 495, in get_groups
MemoryError
```

**Comment by hsoft** [comment]
Windows version of dupeGuru is [currently unmaintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted). That doesn't mean closing this issue, but unless a new Windows maintainer shows up, this issue will not be addressed.

**Comment by arsenetar** [comment]
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.
