### ISSUE TITLE
Error when trying to re-prioritize.

### ISSUE THREAD

**Issue by Sir-Launcelot** [arsenetar/dupeguru#367]
```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\selectable_list.py", line 26, in data
  File "C:\src\dupeguru\hscommon\gui\selectable_list.py", line 115, in __getitem__
IndexError: list index out of range
```

**Comment by ms609** [comment]
Error repeated in v3.9.1
Added column "Modification" to search results
Under 'Re-prioritize', selected 'Filename (Longest)
Error window appeared and drop-down switched to 'modification', listing options 'Newest' and 'Oldest'
Running Windows 7 64 bit.

Error report presented by program:

Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\selectable_list.py", line 26, in data
  File "C:\src\dupeguru\hscommon\gui\selectable_list.py", line 115, in __getitem__
IndexError: list index out of range

**Comment by hsoft** [comment]
Windows version of dupeGuru is [currently unmaintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted). That doesn't mean closing this issue, but unless a new Windows maintainer shows up, this issue will not be addressed.

**Comment by francoisjacques** [comment]
Reproed on funtoo. Removing Windows tag.

```
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qtlib/selectable_list.py", line 26, in data
    return self.model[index.row()]
  File "/usr/share/dupeguru/hscommon/gui/selectable_list.py", line 115, in __getitem__
    return self._items.__getitem__(key)
IndexError: list index out of range
```

**Comment by arsenetar** [comment]
4.0.3 and older versions are rather old versions, I am closing all issues related to them as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
