### ISSUE TITLE
Somekind error i saved 13000lines in text file. First lines pasted.

### ISSUE THREAD

**Issue by kangarooo** [arsenetar/dupeguru#368]
<<<<<<<<<<<<<<<<<<< (First lines of errror) >>>>>>>>>>>>>>

Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\core\fs.py", line 91, in **getattribute**
  File "C:\src\dupeguru\core\fs.py", line 106, in _read_info
  File "C:\src\dupeguru\hscommon\path.py", line 202, in stat
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\Users\Kangarooo\dwhelper\Video\How to Make a Behavior Addictive Zoë Chance at TEDxMillRiver.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\logging__init__.py", line 941, in emit
  File "C:\Python\64-bit\3.3\lib\encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xeb' in position 177: character maps to <undefined>

<<<<<<<<<<<<<<<<<<< (More added to text file) >>>>>>>>>>>>>>

**Comment by kangarooo** [comment]
[DupeGuruError.txt](https://github.com/hsoft/dupeguru/files/280531/DupeGuruError.txt)

**Comment by hsoft** [comment]
Relevant note: Windows version of dupeGuru is [currently unmaintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted)

**Comment by arsenetar** [comment]
The long error repeats appeared to have been a python 3.3 issue, which is resolved in newer versions. The original error is just a file that did not exist.
