### ISSUE TITLE
Error: name 'logging' is not defined

### ISSUE THREAD

**Issue by GarthSnyder** [arsenetar/dupeguru#389]
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.1
Mac OS X Version: Version 10.12 (Build 16A313a)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 316, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 764, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 171, in get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 48, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 109, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 48, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 109, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 48, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 109, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 40, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by GarthSnyder** [comment]
I was doing a folder-mode scan on a group that included one local (to OS X) directory and one that was mounted from a FreeBSD server via SMB.

**Comment by maximveksler** [comment]
```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.4 (Build 16E195)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 776, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 159, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 90, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 257, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 244, in get_file
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/path.py", line 226, in wrapped
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 22, in can_handle
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined
```

**Comment by Dobatymo** [comment]
This should be fixed by now.

**Comment by leocaseiro** [comment]
I think my errors is related to that, but I don't have a clear error log message:


The only thing that I can say is that the error only happens if I run on `Picture` mode as Contents, it's working fine for me on the `Standard` mode.

```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20D74)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/photo/2007/2007-01-14(SOME - PHOTOS)/- 004.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/photo/2007/2007-01-14(SOME - PHOTOS)/- 004.jpg'
```

**Comment by arsenetar** [comment]
These issues should be fixed in the current version.
