### ISSUE TITLE
dupeGuru 4.0.1 crash

### ISSUE THREAD

**Issue by Vinfab** [arsenetar/dupeguru#396]
```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.1
Mac OS X Version: Version 10.12.1 (Build 16B2333a)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 105, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 287, in _job_completed
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 272, in _results_changed
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 33, in notify
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 72, in dispatch
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/stats_label.py", line 20, in results_changed
AttributeError: 'NoneType' object has no attribute 'refresh'
```

**Comment by arsenetar** [comment]
This appears similar to an issue that has been fixed, recommend trying the latest version.

**Comment by arsenetar** [comment]
Closing as this issue is stale now and has most likely been fixed.
