### ISSUE TITLE
Error on Close/exit [Version 4.0.3]

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [arsenetar/dupeguru#405]
I was just adding stuff to the ignore list for a picture based scan before this happened 
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/results_model.py", line 93, in appWillSavePrefs
    self.model.columns.save_columns()
AttributeError: 'NoneType' object has no attribute 'model'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
<hr>
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
<hr>
I think these are getting redundant now

**Comment by matkoniecz** [comment]
The same happens for me on 32 bit Ubuntu 14.04, sometimes model, app, _shown_once cycle happens once, sometimes many times.

I am willing to provide more information it it has chance to be useful.

**Comment by arsenetar** [comment]
I would try the latest version and see if the issue still exists, several errors like this have been fixed.

**Comment by arsenetar** [comment]
Closing as has not been reported on recent versions.
