### ISSUE TITLE
_dbm.error: [Errno 79] Inappropriate file type or format

### ISSUE THREAD

**Issue by interplanetarychris** [arsenetar/dupeguru#437]
I'm doing a very large Picture/Content dupe check on repositories that include Lightroom and Aperture directories on local and SMB filesystems.

`Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.6 (Build 16G29)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format
`

**Comment by arsenetar** [comment]
I believe this has been resolved in the current version.
