### ISSUE TITLE
match sort

### ISSUE THREAD

**Issue by Rparks-33** [arsenetar/dupeguru#495]
In Dupes Only mode. clicked on Match 100%  and got this error

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.4 (Build 17E150g)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/inter/result_table.py", line 31, in sortBy_ascending_
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/result_table.py", line 139, in sort
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 396, in sort_dupes
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 395, in <lambda>
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 190, in _get_dupe_sort_key
AttributeError: 'NoneType' object has no attribute 'percentage'

Please note that dupeGuru is currently
[unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). That means that this
issue is unlikely to be answered in a timely manner.

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
