### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Cadill** [arsenetar/dupeguru#507]
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 101, in pulse
  File "C:\Users\arsen\github\dupeguru\core\app.py", line 323, in _job_error
  File "C:\Users\arsen\github\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\Users\arsen\github\dupeguru\core\app.py", line 780, in do
  File "C:\Users\arsen\github\dupeguru\core\scanner.py", line 137, in get_dupe_groups
  File "C:\Users\arsen\github\dupeguru\core\scanner.py", line 82, in _getmatches
  File "C:\Users\arsen\github\dupeguru\core\engine.py", line 269, in getmatches_by_contents
MemoryError

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
