### ISSUE TITLE
_get_dupe_sort_key Error no 'percentage' attribute

### ISSUE THREAD

**Issue by storyjesse** [arsenetar/dupeguru#516]
Please note that dupeGuru is currently
[unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). That means that this
issue is unlikely to be answered in a timely manner. -- Understood ;-)

I had just unchecked the Delta Values checkbox and selected the Dupes Only, checkbox. This error continues but the rest of the program continued to work fine.

Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 280, in powerMarkerTriggered
    self.resultsModel.power_marker = self.sender().isChecked()
  File "/usr/share/dupeguru/qt/results_model.py", line 81, in power_marker
    self.model.power_marker = value
  File "/usr/share/dupeguru/core/gui/result_table.py", line 156, in power_marker
    self.sort(key, asc)
  File "/usr/share/dupeguru/core/gui/result_table.py", line 139, in sort
    self.app.results.sort_dupes(key, asc, self.delta_values)
  File "/usr/share/dupeguru/core/results.py", line 396, in sort_dupes
    self.__dupes.sort(key=keyfunc, reverse=not asc)
  File "/usr/share/dupeguru/core/results.py", line 395, in <lambda>
    keyfunc = lambda d: self.app._get_dupe_sort_key(d, lambda: self.get_group_of_duplicate(d), key, delta)
  File "/usr/share/dupeguru/core/app.py", line 190, in _get_dupe_sort_key
    return m.percentage
AttributeError: 'NoneType' object has no attribute 'percentage'

**Comment by Seeker14491** [comment]
I got this error too. After scanning my files, I used the "Re-Prioritize Results" action from the Actions menu, then clicked on "Match %" to change the sort order, which triggered this error.

```
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "qt\result_window.py", line 289, in powerMarkerTriggered
  File "qt\results_model.py", line 81, in power_marker
  File "core\gui\result_table.py", line 156, in power_marker
  File "core\gui\result_table.py", line 139, in sort
  File "core\results.py", line 396, in sort_dupes
  File "core\results.py", line 395, in <lambda>
  File "core\app.py", line 190, in _get_dupe_sort_key
AttributeError: 'NoneType' object has no attribute 'percentage'
```

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.
