### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Jahrgang** [arsenetar/dupeguru#549]
Application Identifier: com.hardcoded-software.dupeguru-pe
Application Version: 2.10.1
Mac OS X Version: Version 10.13.6 (Build 17G4015)

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 92, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 59, in reraise_if_error
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru PE.app/Contents/Resources/py/core/app.py", line 743, in do
  File "build/dupeGuru PE.app/Contents/Resources/py/core/scanner.py", line 134, in get_dupe_groups
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/scanner.py", line 21, in _getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 172, in getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/context.py", line 118, in Pool
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/pool.py", line 168, in __init__
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/pool.py", line 233, in _repopulate_pool
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/process.py", line 105, in start
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/context.py", line 267, in _Popen
  File "build/dupeGuru PE.app/Contents/Resources/py/multiprocessing/popen_fork.py", line 19, in __init__
OSError: [Errno 5] Input/output error

Relevant Console logs:

The reading of "/Volumes/home/lost/Pictures/cr2/2006-07-12_04-12-05.cr2" failed with ""

Environment: Google Photos removed files from the scanned folder in the background.

**Comment by arsenetar** [comment]
This may still be an issue in the latest version but I would suggest updating the the latest at: https://dupeguru.voltaicideas.net/
