### ISSUE TITLE
Unknown error -- possible failure to delete due to excessively long filename/path

### ISSUE THREAD

**Issue by smk291** [arsenetar/dupeguru#567]
# Instructions 

# Bug / issue Report
System Information:
 - DupeGuru Version: `4.0.3`
 - Operating System: `Windows/Linux/OSX` `distribution` `version` 

## Debug Log
```
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\projects\dupeguru\hscommon\gui\progress_window.py", line 101, in pulse
  File "C:\projects\dupeguru\core\app.py", line 323, in _job_error
  File "C:\projects\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\projects\dupeguru\core\app.py", line 223, in _do_delete
  File "C:\projects\dupeguru\core\results.py", line 298, in perform_on_marked
  File "C:\projects\dupeguru\core\app.py", line 220, in op
  File "C:\projects\dupeguru\core\app.py", line 236, in _do_delete_dupe
  File "C:\projects\dupeguru\env\lib\site-packages\send2trash\plat_win.py", line 77, in send2trash
  File "C:\Python36-x64\lib\ctypes\__init__.py", line 285, in create_unicode_buffer
ValueError: string too long
```

**Comment by arsenetar** [comment]
Seems most likely to be the same as #611

**Comment by arsenetar** [comment]
Fixed in send2trash, will be fixed in next build of dupeGuru.
