### ISSUE TITLE
Crashes while collecting files to scan

### ISSUE THREAD

**Issue by pcolsen** [arsenetar/dupeguru#585]
# Instructions 
DupGuru fails when beginning to collect files to be scanned.  I've tried this with several different directories, restarting the program several times.  This is a recent failure.  I've been using the program heavily, sometimes scanning as many as 34000+ files.  This was a sudden and complete failure.  I can't get it to collect files in any directory.  The only change I made was to move several files out of a directory before I attempted to scan it.  I had scanned the directory before, but I moved some subdirectories out before trying to scan it again.  I don't believe that I changed anything else that would affect the program's operation.  I cleared the picture cache and tried again but still without success.  The error occurs only in photo mode and only in the "content" mode. The EXIF Timestamp mode works correctly.  The Standard and Music modes work correctly on the same directory.

 Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.5 (Build 18F132)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:65284'

**Comment by lloydc99** [comment]
I get the same error. It had been working for a while but after I cleared out a bunch of duplicates and changed the filters this showed up.

**Comment by arsenetar** [comment]
I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: https://github.com/arsenetar/dupeguru/issues/566#issuecomment-569992117.  If you would like to give one of those a try and let me know if that works that would be helpful. This is most likely related to #439.
