### ISSUE TITLE
File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__

### ISSUE THREAD

**Issue by ElliottVL** [arsenetar/dupeguru#586]
# Instructions 
1. Provide a short descriptive title for the issue. A good example is 'Results window appears off screen.', a non-optimal example is 'Problem with App'.
2. Please fill out either the 'Bug / Issue' or the 'Feature Request' section. Replace values in ` `.
3. Delete these instructions and the unused sections.

# Bug / issue Report
System Information:
 - DupeGuru Version: `version`
 - Operating System: `Windows/Linux/OSX` `distribution` `version` 

If using the source distribution and building yourself also provide (otherwise remove):
 - Python Version: `version ex. 3.6.6` `32/64bit`  
 - Complier: `gcc/llvm/msvc` `version`

## Description
`Provide a detailed description of the issue to help reproduce it.  If it happens after a specific sequence of events provide them here.`

## Debug Log
```
If reporting an error provide the debug log and/or the error message information.  If the debug log is short < 40 lines you can provide it here, otherwise attach the text file to this issue.
```

# Feature Requests
`Provide a detailed description of the feature.`

**Comment by ElliottVL** [comment]
A later problem:
Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 774, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 171, in get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 40, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by arsenetar** [comment]
Duplicate of #389
