### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by keithmorreale** [arsenetar/dupeguru#591]
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\projects\dupeguru\hscommon\gui\progress_window.py", line 101, in pulse
  File "C:\projects\dupeguru\core\app.py", line 323, in _job_error
  File "C:\projects\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\projects\dupeguru\core\app.py", line 780, in do
  File "C:\projects\dupeguru\core\scanner.py", line 137, in get_dupe_groups
  File "C:\projects\dupeguru\core\pe\scanner.py", line 31, in _getmatches
  File "C:\projects\dupeguru\core\pe\matchblock.py", line 167, in getmatches
  File "C:\projects\dupeguru\core\pe\matchblock.py", line 64, in prepare_pictures
  File "C:\projects\dupeguru\core\pe\matchblock.py", line 56, in get_cache
  File "C:\projects\dupeguru\core\pe\cache_sqlite.py", line 10, in <module>
  File "C:\Python36-x64\lib\sqlite3\__init__.py", line 23, in <module>
  File "C:\Python36-x64\lib\sqlite3\dbapi2.py", line 27, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by arsenetar** [comment]
By any chance have you tried the 4.0.4 version?  Does it also have the same issue?  This almost looks like an issue with the sqlite library / python installation here.

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue

**Comment by keithmorreale** [comment]
Thanks for your response, I did not even think to look about an update
prior to posting that. I know I know script kiddie mistake lol. Anyway,
Thanks for the heads-up and am Updating now.
Keith D. Morreale
251 Calcasieu Loop
Leesville, LA 71446
337-353-0910
Schedule a Phone or In Person Meeting.
<https://calendly.com/morrealeestates>
