### ISSUE TITLE
Отчет об ошибке

### ISSUE THREAD

**Issue by RedFoxxe** [arsenetar/dupeguru#662]
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Версия 10.15 (Выпуск 19A583)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/igor/Pictures/Медиатека Фото.photoslibrary/resources/derivatives/masters/F/FAA626FE-A8B0-4D8D-AFD5-E8E6080108B9_4_5005_c.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/igor/Pictures/\xd0\x9c\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb0\xd1\x82\xd0\xb5\xd0\xba\xd0\xb0 \xd0\xa4\xd0\xbe\xd1\x82\xd0\xbe.photoslibrary/resources/derivatives/masters/F/FAA626FE-A8B0-4D8D-AFD5-E8E6080108B9_4_5005_c.jpeg'

**Comment by glubsy** [comment]
Please use the search function the future. This has been reported many times (ref: #439), and supposedly fixed in version 4.0.4.

**Comment by arsenetar** [comment]
I recommend trying the latest version there has been some work to correct this issue.
