### ISSUE TITLE
Error on recovered file

### ISSUE THREAD

**Issue by bgszsk** [arsenetar/dupeguru#732]
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.7 (Build 19H2)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/Visual/Photography/Recovery/Recovery 2020/DNG & NEF from Visual 2019/Recovered Files from Visual 2019/Reconstructed Files/Images/PNG2/P180x105-28729.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/Visual/Photography/Recovery/Recovery 2020/DNG & NEF from Visual 2019/Recovered Files from Visual 2019/Reconstructed Files/Images/PNG2/P180x105-28729.png'
q

**Comment by glubsy** [comment]
Yes, this has been reported multiple times already, please use the search feature before posting a duplicate report. This is fixed in version 4.0.4 already.

**Comment by bgszsk** [comment]
OK. I'm sorry to hear you're seeing the same issue repeatedly submitted. 

The error screen does say:

> Something went wrong, how about reporting the error.

and: 

> Error reports should be reported as Github issues. 

You may find that a clearer instruction to the user in the event of an error reduces the rate of duplicate issue reporting. I see two prompts in the error popup asking me to report. Additionally, the error popup says "bonus point for searching" while here I'm being told "please use the search feature before posting a duplicate report." The former makes it seem like it's unnecessary to search, the latter a requirement. If this is what's desired, that's the language that should be shown to the user with the error.

**Comment by glubsy** [comment]
You raise a good point. That message needs to be updated.
