### ISSUE TITLE
DupeGuru crash?

### ISSUE THREAD

**Issue by ANK73** [arsenetar/dupeguru#735]
Application Name: dupeGuru
Version: 4.0.4

Traceback (most recent call last):
  File "/usr/share/dupeguru/core/directories.py", line 247, in save_to_file
    tree.write(fp, encoding='utf-8')
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 772, in write
    serialize(write, self._root, qnames, namespaces,
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 832, in _get_writer
    yield file.write
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/contextlib.py", line 382, in _exit_wrapper
    callback(*args, **kwds)
OSError: [Errno 28] Spazio esaurito sul device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/directories_dialog.py", line 235, in closeEvent
    self.app.shutdown()
  File "/usr/share/dupeguru/qt/app.py", line 166, in shutdown
    self.model.save()
  File "/usr/share/dupeguru/core/app.py", line 737, in save
    self.directories.save_to_file(op.join(self.appdata, 'last_directories.xml'))
  File "/usr/share/dupeguru/core/directories.py", line 247, in save_to_file
    tree.write(fp, encoding='utf-8')
  File "/usr/share/dupeguru/hscommon/util.py", line 412, in __exit__
    self.fp.close()
OSError: [Errno 28] Spazio esaurito sul device

**Comment by glubsy** [comment]
Somehow you ran out of space when DupeGuru tries to save your last used directories. I assume that means your hard drive is full.
Probably not an issue with Dupeguru.

**Comment by ANK73** [comment]
Yeah, I see. Many thanks however!




Il giorno ven 30 ott 2020 alle ore 17:57 Fuan <notifications@github.com> ha
scritto:
