### ISSUE TITLE
Error when trying to close the "Results" tab, or when running a 2nd scan

### ISSUE THREAD

**Issue by Tailszefox** [arsenetar/dupeguru#738]
**Describe the bug**
This bug seems linked to #704, which was closed as fixed. However, I'm using the latest version compiled from source and still encounter the issue.

When trying to close the "Results" tab after having performed a scan, or when trying to run a new scan after having already performed one, the "Error Report" window appears with the following info:

```
Application Name: dupeGuru
Version: 4.0.4

Traceback (most recent call last):
  File "/home/tails/src/dupeguru/hscommon/gui/progress_window.py", line 109, in pulse
    self._finish_func(self.jobid)
  File "/home/tails/src/dupeguru/core/app.py", line 316, in _job_completed
    self.view.show_results_window()
  File "/home/tails/src/dupeguru/qt/app.py", line 362, in show_results_window
    self.showResultsWindow()
  File "/home/tails/src/dupeguru/qt/app.py", line 226, in showResultsWindow
    self.main_window.showTab(self.resultWindow)
  File "/home/tails/src/dupeguru/qt/tabbed_window.py", line 176, in showTab
    self.setTabVisible(index, True)
  File "/home/tails/src/dupeguru/qt/tabbed_window.py", line 186, in setTabVisible
    return self.tabWidget.setTabVisible(index, value)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'
```
The "Results" tab stays open. Fortunately, when making a new scan, it still contains the new results.

**To Reproduce**
1. Run a scan that produces results
2. Press the X button on the Results tab

**Screenshots**
![Peek 2020-11-18 09-48](https://user-images.githubusercontent.com/890677/99507222-6496ef80-2983-11eb-9cb8-5297a047510a.gif)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 4.0.4 - latest version compiled from the GitHub source

**Comment by Tailszefox** [comment]
Whoops, turns out this was fixed, but the PR that fixes the issue hasn't been merged yet. I tried with https://github.com/glubsy/dupeguru/tree/dev and I didn't encounter the issue. My bad, I got confused thinking the current master branch was the latest version. Closing!
