### ISSUE TITLE
Crashing with 'last_directories.xml' file from older installation

### ISSUE THREAD

**Issue by Harv234** [arsenetar/dupeguru#745]
When I install dupeguru 4.04 on a Linux system (Archlinux) that had an older installation and an existing folder ~/.local/share/Hardcoded\ Software/dupeGuru the app crashes on app startup with the following error(s)

Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 69, in main
    dgapp = DupeGuru()
  File "/usr/share/dupeguru/qt/app.py", line 50, in __init__
    self._setup()
  File "/usr/share/dupeguru/qt/app.py", line 69, in _setup
    self.model.load()
  File "/usr/share/dupeguru/core/app.py", line 554, in load
    self.directories.load_from_file(op.join(self.appdata, 'last_directories.xml'))
  File "/usr/share/dupeguru/core/directories.py", line 215, in load_from_file
    for rdn in root.getiterator('root_directory'):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

Deleting the file 'last_directories.xml' from the folder ~/.local/share/Hardcoded\ Software/dupeGuru solves the problem and dupeguru will start normally for the first time. Next Start results in the same crash again.

Content of the file: (could not attach an xml file so I just copied the content here)

<directories><root_directory path="/home/harvey/mp3" /><root_directory path="/home/harvey/music/Sampler/German Hot 100" /><state path="/home/harvey/Documents/Kamera" value="1" /><state path="/home/harvey/Kamera" value="1" /><state path="/home/harvey/music/Sampler" value="0" /><state path="/home/harvey/music/Sampler/German Hot 100" value="1" /></directories>

**Comment by Harv234** [comment]
Seems already to be fixed in git. Awaiting next version ;)
