### ISSUE TITLE
Crash report for v4.0.4 RC

### ISSUE THREAD

**Issue by Valtarien** [arsenetar/dupeguru#747]
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "qt\result_window.py", line 289, in powerMarkerTriggered
  File "qt\results_model.py", line 81, in power_marker
  File "core\gui\result_table.py", line 156, in power_marker
  File "core\gui\result_table.py", line 139, in sort
  File "core\results.py", line 396, in sort_dupes
  File "core\results.py", line 395, in <lambda>
  File "core\app.py", line 190, in _get_dupe_sort_key
AttributeError: 'NoneType' object has no attribute 'percentage'

**Comment by glubsy** [comment]
Please add the following information:
* Your operating system
* The App mode you were using (Standard, Music, Picture)
* The steps you took to produce the error

I suppose you clicked on the "match %" column name.
This is probably due to the fact that [Group.get_match_of()](https://github.com/arsenetar/dupeguru/blob/master/core/engine.py#L407) returns None, and there is no check in [Dupeguru._get_dupe_sort_key()](https://github.com/arsenetar/dupeguru/blob/master/core/app.py#L202) in case `m` is None.
Would need to make sure what value to return by default before making changes...
