### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ghost** [arsenetar/dupeguru#770]
Application Name: dupeGuru
Version: 4.1.0

Traceback (most recent call last):
  File "qtlib\table.py", line 104, in data
  File "qt\results_model.py", line 43, in _getData
  File "core\gui\result_table.py", line 47, in is_cell_delta
AttributeError: 'list' object has no attribute 'lower'

**Comment by glubsy** [comment]
Operating system?

Steps to reproduce?

**Comment by ghost** [comment]
> Operating system?
> 
> Steps to reproduce?

Windows 10, latest version. And this starting happening when i click to delta. And what is really bad. When i've got 50 duplicate files. this message is shown 50 times...
