### ISSUE TITLE
error

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [arsenetar/dupeguru#778]
```
Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/josephvedadi/Desktop/remote_files/FTP/Neshama/ViberDownloads/url-e5f1869f72a5b6893e33be74fcd83e1c.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/josephvedadi/Desktop/remote_files/FTP/Neshama/ViberDownloads/url-e5f1869f72a5b6893e33be74fcd83e1c.jpg'

**Comment by glubsy** [comment]
Dupeguru version please.

**Comment by oneandonlyonebutyou** [comment]
4.0.3

**Comment by oneandonlyonebutyou** [comment]
what is the latest version?

**Comment by glubsy** [comment]
4.1.0 is the latest release, but MacOS is problematic. You can try a release candidate here https://github.com/arsenetar/dupeguru/files/5778985/dupeguru_osx_cocoa_4_0_4_RC6.dmg.zip

**Comment by oneandonlyonebutyou** [comment]
```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.4
Mac OS X Version: Version 11.1.1 (Build 20C80)

Traceback (most recent call last):
  File "build/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/josephvedadi/Desktop/remote_files/FTP/Neshama/ViberDownloads/url-e5f1869f72a5b6893e33be74fcd83e1c.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/py/cocoa/inter.py", line 259, in pulse
  File "build/py/hscommon/gui/progress_window.py", line 105, in pulse
  File "build/py/core/app.py", line 343, in _job_error
  File "build/py/hscommon/jobprogress/performer.py", line 45, in _async_run
  File "build/py/core/app.py", line 838, in do
  File "build/py/core/scanner.py", line 145, in get_dupe_groups
  File "build/py/core/pe/scanner.py", line 27, in _getmatches
  File "build/py/core/pe/matchblock.py", line 188, in getmatches
  File "build/py/core/pe/matchblock.py", line 69, in prepare_pictures
  File "build/py/core/pe/cache_shelve.py", line 130, in purge_outdated
  File "build/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/josephvedadi/Desktop/remote_files/FTP/Neshama/ViberDownloads/url-e5f1869f72a5b6893e33be74fcd83e1c.jpg'

**Comment by glubsy** [comment]
Try removing the cache files and try again.

**Comment by oneandonlyonebutyou** [comment]
How should I delete them ??

**Comment by arsenetar** [comment]
This is most likely fixed in the newer version.  There are builds for macOS there.

**Comment by arsenetar** [comment]
Duplicate of #439.  Clearing the cache via the file menu may resolve this as well.  If issue persists in latest version this may be reopened.
