### ISSUE TITLE
Crash while scanning a large number of photos

### ISSUE THREAD

**Issue by sarain** [arsenetar/dupeguru#848]
I received the following crash report while attempting to scan for duplicates among a large number of photos in the Picture Application Mode with Scan Type set to Contents.   dupeguru was using around 9GB of my RAM when I discovered the crash.

```
Application Name: dupeGuru
Version: 4.1.0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 847, in do
  File "core\scanner.py", line 145, in get_dupe_groups
  File "core\pe\scanner.py", line 27, in _getmatches
  File "core\pe\matchblock.py", line 256, in getmatches
MemoryError
```

**Comment by glubsy** [comment]
Can you give the approximate number of files you added to be scanned?

**Comment by sarain** [comment]
Approximately 300k-400k image files.
After receiving this message, I was able to relaunch dupeGuru and re-scan them successfully in EXIF Timestamp mode.

**Comment by kyrieel** [comment]
I have similar issue.  OSX 10.14.6, Dupe Guru v4.03.  Issue comes when scanning image files under Application mode, "Picture", scan type "Contents". The State settings make no change.  No issue when scanning with Application mode, "Standard", scan type "Contents".  Issue is also found on second Mac with same set up.  
(Now this is strange:  I started DG again to get error so I could copy the error information, but now it works perfectly!) 
This is the error text from the other Mac:
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.6 (Build 18G103)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/External 1/Users/*******/Pictures/My Photos/2008/11 November 2008/20081109-20081109-20081109-open6-2.JPG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/External 1/Users/*********/Pictures/My Photos/2008/11 November 2008/20081109-20081109-20081109-open6-2.JPG'
