### ISSUE TITLE
Crash ValueError: string too long

### ISSUE THREAD

**Issue by TrashAccount3424** [arsenetar/dupeguru#854]
**Describe the bug**
Application Name: dupeGuru
Version: 4.1.0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 243, in _do_delete
  File "core\results.py", line 316, in perform_on_marked
  File "core\app.py", line 238, in op
  File "core\app.py", line 256, in _do_delete_dupe
  File "send2trash\plat_win.py", line 77, in send2trash
  File "ctypes\__init__.py", line 291, in create_unicode_buffer
ValueError: string too long

It happens while deleting files but its obviously related to the file name/path not the action

**To Reproduce**
none - see above it depends on the filename/path not the user action

**Expected behavior**
-obvious

**Screenshots**
-not needed

**Desktop (please complete the following information):**
Windows 10 
Version 4.1.0

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by arsenetar** [comment]
This would be a bug in [send2trash](https://github.com/arsenetar/send2trash), additionally without additional information on the paths trying to be trashed it will be hard to determine why the error is occurring.  I cannot reproduce this error at this time.

**Comment by TrashAccount3424** [comment]
> 
> 
> This would be a bug in [send2trash](https://github.com/arsenetar/send2trash), additionally without additional information on the paths trying to be trashed it will be hard to determine why the error is occurring. I cannot reproduce this error at this time.

I did manage to reproduce it simply by adding some emoji like 😇 in the folder name
Must be have something to do with
`File "ctypes_init.py", line 291, in create_unicode_buffer`
not handling unicode correctly

**Comment by arsenetar** [comment]
Awesome, this is very helpful, apparently it has to do with a difference between pythons string length value and the value for create_unicode_buffer() length.  I think i got this fixed over in send2trash now, and added tests over there.

**Comment by marmathsen** [comment]
Looks like version 4.1.1 still has this issue FYI. Caused by emoji in folder name

Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 243, in _do_delete
  File "core\results.py", line 316, in perform_on_marked
  File "core\app.py", line 238, in op
  File "core\app.py", line 256, in _do_delete_dupe
  File "send2trash\plat_win.py", line 77, in send2trash
  File "ctypes\__init__.py", line 291, in create_unicode_buffer
ValueError: string too long

**Comment by arsenetar** [comment]
Fixing this in dupeGuru requires a new release as it needs to use a new version of the send2trash library.
