### ISSUE TITLE
'NoneType' object has no attribute 'get_display_info'

### ISSUE THREAD

**Issue by Pack-Attacks** [arsenetar/dupeguru#891]
Report from Application:

Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "qtlib\table.py", line 85, in data
  File "qt\results_model.py", line 39, in _getData
  File "core\gui\result_table.py", line 43, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'

**Comment by glubsy** [comment]
This has already been reported and fixed.

**Comment by arsenetar** [comment]
This should be a duplicate error that has been fixed in #905, recommend using the latest version at this point.
