### ISSUE TITLE
Crashes when reading files that begin with "."

### ISSUE THREAD

**Issue by adamsaltman** [arsenetar/dupeguru#906]
Should these files (remnants of deleted files on macOS) that begin with "." be deleted prior to scanning? Here's the error traceback:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20F71)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 169, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 39, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 77, in _compute_maxid
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 77, in <genexpr>
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 95, in __iter__
SystemError: Negative size passed to PyBytes_FromStringAndSize

Relevant Console logs:

The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._334.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._336.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._338.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._340.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._342.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._344.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._346.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._348.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._350.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._352.jpg" failed with ""
The reading of "/Volumes/Photographs/2006/12/31/Thumbs/._354.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Anna Passport_face0.jpg" failed with ""
cannot add item to database
The reading of "/Volumes/Photographs/2006-02-10/._Anna Passport.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Bari Passport_face0.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Bari Passport.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Scan1_face0.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Scan1.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Scan10001_face0.jpg" failed with ""
The reading of "/Volumes/Photographs/2006-02-10/._Scan10001.jpg" failed with ""

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.
