### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by alfesp1** [arsenetar/dupeguru#909]
**Describe the bug**
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 101, in pulse
  File "core\app.py", line 323, in _job_error
  File "hscommon\jobprogress\performer.py", line 43, in _async_run
  File "core\app.py", line 780, in do
  File "core\scanner.py", line 137, in get_dupe_groups
  File "core\scanner.py", line 82, in _getmatches
  File "core\engine.py", line 269, in getmatches_by_contents
MemoryError

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by glubsy** [comment]
Thanks for reporting. Please edit the template and fill in the missing information. 

The application probably ran out of memory. It can happen depending on the amount of files you attempted to scan.

Roughly how many files were you scanning? What Application Mode where you using (Standard, Music or Picture?) and what Scan Type?

Also, it would be helpful if you could activate debug mode and post the logs generated by Dupeguru whenever the crash occurs again.

You should also try the latest version available, as 4.0.4 is now obsolete, this may have been fixed in more recent commits.
