### ISSUE TITLE
Crash after scanning two folders and 3394 pictures

### ISSUE THREAD

**Issue by MilesFarber** [arsenetar/dupeguru#912]
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 101, in pulse
  File "core\app.py", line 323, in _job_error
  File "hscommon\jobprogress\performer.py", line 43, in _async_run
  File "core\app.py", line 780, in do
  File "core\scanner.py", line 137, in get_dupe_groups
  File "core\pe\scanner.py", line 31, in _getmatches
  File "core\pe\matchblock.py", line 169, in getmatches
  File "core\pe\matchblock.py", line 54, in get_cache
  File "core\pe\cache_shelve.py", line 38, in __init__
  File "shelve.py", line 243, in open
  File "shelve.py", line 227, in __init__
  File "dbm\__init__.py", line 94, in open
  File "dbm\dumb.py", line 329, in open
  File "dbm\dumb.py", line 71, in __init__
  File "dbm\dumb.py", line 111, in _update
  File "ast.py", line 46, in literal_eval
  File "ast.py", line 35, in parse
  File "<unknown>", line 1
    'path:X:\\Documents\\Pictures\\
                                  ^
SyntaxError: EOL while scanning string literal

**Comment by glubsy** [comment]
> File "shelve.py", line 227, in init
File "dbm_init.py", line 94, in open
File "dbm\dumb.py", line 329, in open
File "dbm\dumb.py", line 71, in init
File "dbm\dumb.py", line 111, in _update
File "ast.py", line 46, in literal_eval
File "ast.py", line 35, in parse

Where did you download Dupeguru from? There is no "dbm" module in the source tree as far as I known. Is this module injected specifically when running in Microsoft Windows? Try with the latest released version or the latest commit. 4.0.4 is outdated.

**Comment by MilesFarber** [comment]
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 847, in do
  File "core\scanner.py", line 145, in get_dupe_groups
  File "core\pe\scanner.py", line 27, in _getmatches
  File "core\pe\matchblock.py", line 188, in getmatches
  File "core\pe\matchblock.py", line 68, in prepare_pictures
  File "core\pe\matchblock.py", line 56, in get_cache
  File "core\pe\cache_shelve.py", line 45, in __init__
  File "shelve.py", line 243, in open
  File "shelve.py", line 227, in __init__
  File "dbm\__init__.py", line 95, in open
  File "dbm\dumb.py", line 316, in open
  File "dbm\dumb.py", line 71, in __init__
  File "dbm\dumb.py", line 105, in _update
  File "ast.py", line 59, in literal_eval
  File "ast.py", line 47, in parse
ValueError: source code string cannot contain null bytes

**Comment by glubsy** [comment]
Can you try using the "sqlite" picture cache mode and see if you still get the error?

You can select "sqlite" by selecting Picture App mode -> More Options -> Picture Cache Mode.
