### ISSUE TITLE
'DetailsPanel' object has no attribute '_table error when closing the program

### ISSUE THREAD

**Issue by PhilipSharman** [arsenetar/dupeguru#946]
**Describe the bug**
FYI: I got this error message when closing the program:
```
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "qt/details_table.py", line 64, in headerData
  File "core/gui/details_panel.py", line 42, in row_count
AttributeError: 'DetailsPanel' object has no attribute '_table
```
**To Reproduce**
I haven't been able to reproduce it.

**Desktop**
 - OS: MacOS 10.15.7 (Catalina)
 - DupeGuru Version: 4.1.1

**Additional context**
This may be related to issue #857 (which has been closed).

Thanks!

**Comment by VashJuan** [comment]
I just got: 
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "qt\details_table.py", line 64, in headerData
  File "core\gui\details_panel.py", line 42, in row_count
AttributeError: 'DetailsPanel' object has no attribute '_table'

using latest DupeGuru (v4.1.1), but it did its work fine, so no blocking issue for me.

**Comment by glubsy** [comment]
4.1.1 is an outdated version, please try the latest version as this bug should be fixed by now.

Edit: on second thought, maybe this wasn't fixed after all. Anyway, need to reproduce with latest version. Looks like a race condition somewhere?
