### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by K0-RR** [arsenetar/dupeguru#949]
**Describe the bug**
Can't run.

**To Reproduce**
Try to run it
Get this
```
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 89, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 72, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
ModuleNotFoundError: No module named 'core.pe._block'
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version 4.1.1

**Comment by glubsy** [comment]
Need more information. What exactly was executed? Which package, what is the source (release page?)? Did you build from source yourself?

**Comment by arsenetar** [comment]
This is due to the version of python on Ubuntu 21.04, see #484. This is effectively a duplicate as well.
