### ISSUE TITLE
Pictures>Contents mode fails every time

### ISSUE THREAD

**Issue by adamprattchaos** [arsenetar/dupeguru#953]
**Describe the bug**
When I run the Picture>Contents mode it fails with an error. I've even run it on two matching JPEGs as a simple test and it fails.

**To Reproduce**
1. Load two folders, each with the same JPEG.
2. Set the Application Mode to Picture
3. Set the Scan Type to Content
4. Click Scan

**Expected behavior**
I expect the app to identify any duplicates. Instead I get this error message:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.6 (Build 18G9323)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:472378'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6
 - Version 4.0.3 I've tried to install 4.1.1 but my overzealous Mac OS won't let me launch it because of security concerns. Any guidance?

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by arsenetar** [comment]
Well 4.0.3 is just not supported at this point, deleting the picture cache database may fix it.  You can open up the security settings after it prevents you from launching the app and add an exception for the app (there is a prompt that will be there) for the new version.

**Comment by adamprattchaos** [comment]
﻿Thanks for your assistance Andrew. I was able to open the app with a Control-click>Open and purged the Picture cache, but it still fails and I get this error. Is there anything else I can try?

 

Application Identifier: com.hardcoded-software.dupeguru

Application Version: 4.1.1

Mac OS X Version: Version 10.14.6 (Build 18G9323)

 

Traceback (most recent call last):

  File "build/py/cocoa/inter.py", line 259, in pulse

  File "build/py/hscommon/gui/progress_window.py", line 105, in pulse

  File "build/py/core/app.py", line 347, in _job_error

  File "build/py/hscommon/jobprogress/performer.py", line 45, in _async_run

  File "build/py/core/app.py", line 847, in do

  File "build/py/core/scanner.py", line 145, in get_dupe_groups

  File "build/py/core/pe/scanner.py", line 27, in _getmatches

  File "build/py/core/pe/matchblock.py", line 192, in getmatches

  File "build/py/core/pe/matchblock.py", line 56, in get_cache

  File "build/py/core/pe/cache_shelve.py", line 46, in __init__

  File "build/py/core/pe/cache_shelve.py", line 84, in _compute_maxid

  File "build/py/core/pe/cache_shelve.py", line 85, in <genexpr>

  File "build/py/shelve.py", line 96, in __iter__

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 362: invalid start byte

 

Relevant Console logs:

 

Error while loading /Users/apratt/Library/Application Support/dupeGuru/exclude_list.xml: [Errno 2] No such file or directory: '/Users/apratt/Library/Application Support/dupeGuru/exclude_list.xml'

cannot add item to database

cannot add item to database

 

 

From: Andrew Senetar ***@***.***>
Reply-To: arsenetar/dupeguru ***@***.***>
Date: Wednesday, November 3, 2021 at 12:12 AM
To: arsenetar/dupeguru ***@***.***>
Cc: adamprattchaos ***@***.***>, Author ***@***.***>
Subject: Re: [arsenetar/dupeguru] Pictures>Contents mode fails every time (Issue #953)

 

Well 4.0.3 is just not supported at this point, deleting the picture cache database may fix it. You can open up the security settings after it prevents you from launching the app and add an exception for the app (there is a prompt that will be there) for the new version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arsenetar** [comment]
Hmm, I have not seen this specific error before that I can tell. Inside the Application data directory which should be `/Users/apratt/Library/Application Support/dupeGuru/` for you there should be a `cached_pictures.shelve` file, you could delete that if it exists and see if that changes anything for you.  It looks like you are using the cocoa version of 4.1.1, you could try the Qt version of 4.1.1 instead and see if that behaves any differently.
