### ISSUE TITLE
Dupe Guru Exception

### ISSUE THREAD

**Issue by johnfredbarry** [arsenetar/dupeguru#966]
My apologies up front, I haven't coded since 1996, so I don't have the wherewithal to provide more info than below:

Scan on a mounted 128GB microSD, FAT32 Volume 

*Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.1.1
Mac OS X Version: Version 11.6.2 (Build 20G314)

I would be glad to answer any other questions or run more scans

Traceback (most recent call last):
  File "build/py/cocoa/inter.py", line 259, in pulse
  File "build/py/hscommon/gui/progress_window.py", line 109, in pulse
  File "build/py/core/app.py", line 316, in _job_completed
  File "build/py/core/app.py", line 301, in _results_changed
  File "build/py/hscommon/notify.py", line 35, in notify
  File "build/py/hscommon/notify.py", line 75, in dispatch
  File "build/py/core/gui/stats_label.py", line 21, in results_changed
AttributeError: 'NoneType' object has no attribute 'refresh'

**Comment by arsenetar** [comment]
I believe this is resolved since the release of 4.1.1, next released version should no longer have the issue.

**Comment by arsenetar** [comment]
@johnfredbarry The new version is out, I recommend giving that a try.
