### ISSUE TITLE
Error when delete after scan, latest commit.

### ISSUE THREAD

**Issue by chchia** [arsenetar/dupeguru#988]
**Describe the bug**

**To Reproduce**
Trying to delete duplicate after scan completed, and i got this error

`Application Name: dupeGuru
Version: 4.2.1
Python: 3.8.10
Operating System: Linux-5.14.0-1031-oem-x86_64-with-glibc2.29

Traceback (most recent call last):
  File "/home/chchia/dupeguru/hscommon/gui/progress_window.py", line 102, in pulse
    should_continue = self._error_func(self.jobid, err)
  File "/home/chchia/dupeguru/core/app.py", line 330, in _job_error
    raise err
  File "/home/chchia/dupeguru/hscommon/jobprogress/performer.py", line 45, in _async_run
    target(*args)
  File "/home/chchia/dupeguru/core/app.py", line 232, in _do_delete
    self.results.perform_on_marked(op, True)
  File "/home/chchia/dupeguru/core/results.py", line 302, in perform_on_marked
    func(dupe)
  File "/home/chchia/dupeguru/core/app.py", line 229, in op
    return self._do_delete_dupe(dupe, link_deleted, use_hardlinks, direct_deletion)
  File "/home/chchia/dupeguru/core/app.py", line 251, in _do_delete_dupe
    self.clean_empty_dirs(dupe.path.parent())
TypeError: 'PosixPath' object is not callable`

**Comment by arsenetar** [comment]
Thanks for catching that, that was missed in the pathlib changes.

**Comment by chchia** [comment]
thanks, thats so promptly!

and i had to say the latest os.scan method really make huge different for scanning speed!
