### ISSUE TITLE
scanning very large number of files, possibly without having assigned one folder as reference

### ISSUE THREAD

**Issue by ChrisFryBarcelona** [arsenetar/dupeguru#991]
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 847, in do
  File "core\scanner.py", line 145, in get_dupe_groups
  File "core\scanner.py", line 90, in _getmatches
  File "core\engine.py", line 295, in getmatches_by_contents
MemoryError

I'm going to try again making sure that there is one folder marked as Reference

**Comment by ChrisFryBarcelona** [comment]
I tried again making quite sure I had assigned one of the folders as Reference. It took all night to find 170374 duplicates and then about six hours to delete them all.
I deduce that the cause of the issue was not assigning one of the folders as Reference, maybe combines with the very large number of files.

**Comment by arsenetar** [comment]
The memory error should be related to the system's RAM and dupeGuru unable to allocate memory for further operations.  There is some future work planned to look into /optimize usage a bit more.  The memory usage can be monitored with system tools such as task manager on windows.  Seems like the system here was running out of memory and potentially using swap causing some of the slowness in the operations.

**Comment by bphd** [comment]
Same, eats up all RAM then freeze. Can't he write its working data on temporary files? Because RAM is not reliable for big comparison
