### ISSUE TITLE
dupeGuru

### ISSUE THREAD

**Issue by JohnrC123** [arsenetar/dupeguru#992]
**The app suggests reporting the error so hear it is (happened while scanning for duplicates on a C:\ with a lot of files):**

Application Name: dupeGuru
Version: 4.2.1
Python: 3.8.13
Operating System: Windows-10-10.0.19044-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 102, in pulse
  File "core\app.py", line 330, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 811, in do
  File "core\scanner.py", line 174, in get_dupe_groups
  File "core\scanner.py", line 174, in <listcomp>
MemoryError

**Cheers**

**Comment by arsenetar** [comment]
Likely this happened due to the system running out of RAM.  You can monitor this when running a scan with task manager on windows.  There will be some work in the future to see if memory usage can be improved, but might not resolve it for all cases.

**Comment by bphd** [comment]
Same, eats up all RAM then freeze. Can't he write its working data on temporary files? Because RAM is not reliable for big comparison
